// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: fvs2d.proto

// v1 compatibility policy: fields and messages are additive within v1;
// existing field numbers/names are never reused. A field or message that is
// renamed or removed must have its old number/name added to a `reserved`
// declaration in the same change.

package fvs2dpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnmountMode int32

const (
	UnmountMode_UNMOUNT_MODE_NORMAL UnmountMode = 0
	UnmountMode_UNMOUNT_MODE_LAZY   UnmountMode = 1
)

// Enum value maps for UnmountMode.
var (
	UnmountMode_name = map[int32]string{
		0: "UNMOUNT_MODE_NORMAL",
		1: "UNMOUNT_MODE_LAZY",
	}
	UnmountMode_value = map[string]int32{
		"UNMOUNT_MODE_NORMAL": 0,
		"UNMOUNT_MODE_LAZY":   1,
	}
)

func (x UnmountMode) Enum() *UnmountMode {
	p := new(UnmountMode)
	*p = x
	return p
}

func (x UnmountMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnmountMode) Descriptor() protoreflect.EnumDescriptor {
	return file_fvs2d_proto_enumTypes[0].Descriptor()
}

func (UnmountMode) Type() protoreflect.EnumType {
	return &file_fvs2d_proto_enumTypes[0]
}

func (x UnmountMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnmountMode.Descriptor instead.
func (UnmountMode) EnumDescriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{0}
}

type ChangeKind int32

const (
	ChangeKind_CHANGE_KIND_UNSPECIFIED ChangeKind = 0
	ChangeKind_CHANGE_KIND_ADDED       ChangeKind = 1
	ChangeKind_CHANGE_KIND_MODIFIED    ChangeKind = 2
	ChangeKind_CHANGE_KIND_REMOVED     ChangeKind = 3
)

// Enum value maps for ChangeKind.
var (
	ChangeKind_name = map[int32]string{
		0: "CHANGE_KIND_UNSPECIFIED",
		1: "CHANGE_KIND_ADDED",
		2: "CHANGE_KIND_MODIFIED",
		3: "CHANGE_KIND_REMOVED",
	}
	ChangeKind_value = map[string]int32{
		"CHANGE_KIND_UNSPECIFIED": 0,
		"CHANGE_KIND_ADDED":       1,
		"CHANGE_KIND_MODIFIED":    2,
		"CHANGE_KIND_REMOVED":     3,
	}
)

func (x ChangeKind) Enum() *ChangeKind {
	p := new(ChangeKind)
	*p = x
	return p
}

func (x ChangeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_fvs2d_proto_enumTypes[1].Descriptor()
}

func (ChangeKind) Type() protoreflect.EnumType {
	return &file_fvs2d_proto_enumTypes[1]
}

func (x ChangeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeKind.Descriptor instead.
func (ChangeKind) EnumDescriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{1}
}

type ListCommitsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepositoryPath string                 `protobuf:"bytes,1,opt,name=repository_path,json=repositoryPath,proto3" json:"repository_path,omitempty"`
	// page_size caps the number of summaries returned (default: all).
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// page_token resumes a previous listing, opaque, echoed from
	// next_page_token.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommitsRequest) Reset() {
	*x = ListCommitsRequest{}
	mi := &file_fvs2d_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommitsRequest) ProtoMessage() {}

func (x *ListCommitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommitsRequest.ProtoReflect.Descriptor instead.
func (*ListCommitsRequest) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{0}
}

func (x *ListCommitsRequest) GetRepositoryPath() string {
	if x != nil {
		return x.RepositoryPath
	}
	return ""
}

func (x *ListCommitsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCommitsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListCommitsResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Commits []*CommitSummary       `protobuf:"bytes,2,rep,name=commits,proto3" json:"commits,omitempty"`
	// next_page_token is set when more results follow; pass it back as
	// page_token to continue.
	NextPageToken string `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommitsResponse) Reset() {
	*x = ListCommitsResponse{}
	mi := &file_fvs2d_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommitsResponse) ProtoMessage() {}

func (x *ListCommitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommitsResponse.ProtoReflect.Descriptor instead.
func (*ListCommitsResponse) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{1}
}

func (x *ListCommitsResponse) GetCommits() []*CommitSummary {
	if x != nil {
		return x.Commits
	}
	return nil
}

func (x *ListCommitsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetCommitRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RepositoryPath  string                 `protobuf:"bytes,1,opt,name=repository_path,json=repositoryPath,proto3" json:"repository_path,omitempty"`
	StateIdOrPrefix string                 `protobuf:"bytes,2,opt,name=state_id_or_prefix,json=stateIdOrPrefix,proto3" json:"state_id_or_prefix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetCommitRequest) Reset() {
	*x = GetCommitRequest{}
	mi := &file_fvs2d_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommitRequest) ProtoMessage() {}

func (x *GetCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommitRequest.ProtoReflect.Descriptor instead.
func (*GetCommitRequest) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{2}
}

func (x *GetCommitRequest) GetRepositoryPath() string {
	if x != nil {
		return x.RepositoryPath
	}
	return ""
}

func (x *GetCommitRequest) GetStateIdOrPrefix() string {
	if x != nil {
		return x.StateIdOrPrefix
	}
	return ""
}

type RestoreRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RepositoryPath  string                 `protobuf:"bytes,1,opt,name=repository_path,json=repositoryPath,proto3" json:"repository_path,omitempty"`
	StateIdOrPrefix string                 `protobuf:"bytes,2,opt,name=state_id_or_prefix,json=stateIdOrPrefix,proto3" json:"state_id_or_prefix,omitempty"`
	// destination_path overrides the restore destination (default: the repo root).
	DestinationPath *string `protobuf:"bytes,3,opt,name=destination_path,json=destinationPath,proto3,oneof" json:"destination_path,omitempty"`
	// clean removes files in the destination that are not part of the state.
	Clean bool `protobuf:"varint,4,opt,name=clean,proto3" json:"clean,omitempty"`
	// reset moves HEAD to the restored state.
	Reset_        bool `protobuf:"varint,5,opt,name=reset,proto3" json:"reset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_fvs2d_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{3}
}

func (x *RestoreRequest) GetRepositoryPath() string {
	if x != nil {
		return x.RepositoryPath
	}
	return ""
}

func (x *RestoreRequest) GetStateIdOrPrefix() string {
	if x != nil {
		return x.StateIdOrPrefix
	}
	return ""
}

func (x *RestoreRequest) GetDestinationPath() string {
	if x != nil && x.DestinationPath != nil {
		return *x.DestinationPath
	}
	return ""
}

func (x *RestoreRequest) GetClean() bool {
	if x != nil {
		return x.Clean
	}
	return false
}

func (x *RestoreRequest) GetReset_() bool {
	if x != nil {
		return x.Reset_
	}
	return false
}

type RestoreResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StateId         string                 `protobuf:"bytes,1,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	DestinationPath string                 `protobuf:"bytes,2,opt,name=destination_path,json=destinationPath,proto3" json:"destination_path,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_fvs2d_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{4}
}

func (x *RestoreResponse) GetStateId() string {
	if x != nil {
		return x.StateId
	}
	return ""
}

func (x *RestoreResponse) GetDestinationPath() string {
	if x != nil {
		return x.DestinationPath
	}
	return ""
}

type InitRepositoryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepositoryPath string                 `protobuf:"bytes,1,opt,name=repository_path,json=repositoryPath,proto3" json:"repository_path,omitempty"`
	BlockSize      uint32                 `protobuf:"varint,2,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InitRepositoryRequest) Reset() {
	*x = InitRepositoryRequest{}
	mi := &file_fvs2d_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRepositoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRepositoryRequest) ProtoMessage() {}

func (x *InitRepositoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRepositoryRequest.ProtoReflect.Descriptor instead.
func (*InitRepositoryRequest) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{5}
}

func (x *InitRepositoryRequest) GetRepositoryPath() string {
	if x != nil {
		return x.RepositoryPath
	}
	return ""
}

func (x *InitRepositoryRequest) GetBlockSize() uint32 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

type Repository struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepositoryPath string                 `protobuf:"bytes,1,opt,name=repository_path,json=repositoryPath,proto3" json:"repository_path,omitempty"`
	BlockSize      uint32                 `protobuf:"varint,2,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Repository) Reset() {
	*x = Repository{}
	mi := &file_fvs2d_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{6}
}

func (x *Repository) GetRepositoryPath() string {
	if x != nil {
		return x.RepositoryPath
	}
	return ""
}

func (x *Repository) GetBlockSize() uint32 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

type CommitRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepositoryPath string                 `protobuf:"bytes,1,opt,name=repository_path,json=repositoryPath,proto3" json:"repository_path,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AllowEmpty     bool                   `protobuf:"varint,3,opt,name=allow_empty,json=allowEmpty,proto3" json:"allow_empty,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_fvs2d_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{7}
}

func (x *CommitRequest) GetRepositoryPath() string {
	if x != nil {
		return x.RepositoryPath
	}
	return ""
}

func (x *CommitRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommitRequest) GetAllowEmpty() bool {
	if x != nil {
		return x.AllowEmpty
	}
	return false
}

type Commit struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepositoryPath string                 `protobuf:"bytes,1,opt,name=repository_path,json=repositoryPath,proto3" json:"repository_path,omitempty"`
	StateId        string                 `protobuf:"bytes,2,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FileCount      uint64                 `protobuf:"varint,4,opt,name=file_count,json=fileCount,proto3" json:"file_count,omitempty"`
	Message        string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	// created is false when the commit was a no-op (state_id/message/
	// created_at describe the pre-existing HEAD state, not a new one).
	Created       bool `protobuf:"varint,6,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Commit) Reset() {
	*x = Commit{}
	mi := &file_fvs2d_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit) ProtoMessage() {}

func (x *Commit) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit.ProtoReflect.Descriptor instead.
func (*Commit) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{8}
}

func (x *Commit) GetRepositoryPath() string {
	if x != nil {
		return x.RepositoryPath
	}
	return ""
}

func (x *Commit) GetStateId() string {
	if x != nil {
		return x.StateId
	}
	return ""
}

func (x *Commit) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Commit) GetFileCount() uint64 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

func (x *Commit) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Commit) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

// CommitSummary is the cheap, list-friendly projection of a Commit: no
// nested data, safe to fetch in bulk. Fetch full detail with GetCommit.
type CommitSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepositoryPath string                 `protobuf:"bytes,1,opt,name=repository_path,json=repositoryPath,proto3" json:"repository_path,omitempty"`
	StateId        string                 `protobuf:"bytes,2,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Message        string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	FileCount      uint64                 `protobuf:"varint,5,opt,name=file_count,json=fileCount,proto3" json:"file_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommitSummary) Reset() {
	*x = CommitSummary{}
	mi := &file_fvs2d_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitSummary) ProtoMessage() {}

func (x *CommitSummary) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitSummary.ProtoReflect.Descriptor instead.
func (*CommitSummary) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{9}
}

func (x *CommitSummary) GetRepositoryPath() string {
	if x != nil {
		return x.RepositoryPath
	}
	return ""
}

func (x *CommitSummary) GetStateId() string {
	if x != nil {
		return x.StateId
	}
	return ""
}

func (x *CommitSummary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CommitSummary) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommitSummary) GetFileCount() uint64 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

// Progress reports incremental status for a streaming Commit/Restore. Phase
// is a short machine-friendly tag ("hashing", "restoring", "done"); message
// carries the current file path when known. done=true marks the final
// message on the stream, together with whichever result field applies.
type Progress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	Current       int64                  `protobuf:"varint,2,opt,name=current,proto3" json:"current,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Done          bool                   `protobuf:"varint,5,opt,name=done,proto3" json:"done,omitempty"`
	ResultCommit  *Commit                `protobuf:"bytes,6,opt,name=result_commit,json=resultCommit,proto3" json:"result_commit,omitempty"`
	ResultRestore *RestoreResponse       `protobuf:"bytes,7,opt,name=result_restore,json=resultRestore,proto3" json:"result_restore,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_fvs2d_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{10}
}

func (x *Progress) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *Progress) GetCurrent() int64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *Progress) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Progress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Progress) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *Progress) GetResultCommit() *Commit {
	if x != nil {
		return x.ResultCommit
	}
	return nil
}

func (x *Progress) GetResultRestore() *RestoreResponse {
	if x != nil {
		return x.ResultRestore
	}
	return nil
}

type ProbeResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	DaemonVersion        string                 `protobuf:"bytes,1,opt,name=daemon_version,json=daemonVersion,proto3" json:"daemon_version,omitempty"`
	Pid                  uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	StartedAt            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FuseBackendAvailable bool                   `protobuf:"varint,4,opt,name=fuse_backend_available,json=fuseBackendAvailable,proto3" json:"fuse_backend_available,omitempty"`
	DevFuseAccessible    bool                   `protobuf:"varint,5,opt,name=dev_fuse_accessible,json=devFuseAccessible,proto3" json:"dev_fuse_accessible,omitempty"`
	FusermountAvailable  bool                   `protobuf:"varint,6,opt,name=fusermount_available,json=fusermountAvailable,proto3" json:"fusermount_available,omitempty"`
	RunningInFlatpak     bool                   `protobuf:"varint,7,opt,name=running_in_flatpak,json=runningInFlatpak,proto3" json:"running_in_flatpak,omitempty"`
	// api_version identifies this proto's wire contract (independent of
	// daemon_version, which is the build's own version string).
	ApiVersion string `protobuf:"bytes,8,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// min_repo_format / max_repo_format bound the on-disk fvs2 repo formats
	// this daemon build can read/write.
	MinRepoFormat uint32 `protobuf:"varint,9,opt,name=min_repo_format,json=minRepoFormat,proto3" json:"min_repo_format,omitempty"`
	MaxRepoFormat uint32 `protobuf:"varint,10,opt,name=max_repo_format,json=maxRepoFormat,proto3" json:"max_repo_format,omitempty"`
	// supported_operations lists the Fvs2d RPC method names this build
	// implements, for simple client-side capability checks.
	SupportedOperations []string `protobuf:"bytes,11,rep,name=supported_operations,json=supportedOperations,proto3" json:"supported_operations,omitempty"`
	// work_dir is the configured allowed-root (--root), empty when the
	// daemon has no sandbox configured and serves arbitrary paths.
	WorkDir       *string `protobuf:"bytes,12,opt,name=work_dir,json=workDir,proto3,oneof" json:"work_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeResponse) Reset() {
	*x = ProbeResponse{}
	mi := &file_fvs2d_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResponse) ProtoMessage() {}

func (x *ProbeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResponse.ProtoReflect.Descriptor instead.
func (*ProbeResponse) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{11}
}

func (x *ProbeResponse) GetDaemonVersion() string {
	if x != nil {
		return x.DaemonVersion
	}
	return ""
}

func (x *ProbeResponse) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProbeResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ProbeResponse) GetFuseBackendAvailable() bool {
	if x != nil {
		return x.FuseBackendAvailable
	}
	return false
}

func (x *ProbeResponse) GetDevFuseAccessible() bool {
	if x != nil {
		return x.DevFuseAccessible
	}
	return false
}

func (x *ProbeResponse) GetFusermountAvailable() bool {
	if x != nil {
		return x.FusermountAvailable
	}
	return false
}

func (x *ProbeResponse) GetRunningInFlatpak() bool {
	if x != nil {
		return x.RunningInFlatpak
	}
	return false
}

func (x *ProbeResponse) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *ProbeResponse) GetMinRepoFormat() uint32 {
	if x != nil {
		return x.MinRepoFormat
	}
	return 0
}

func (x *ProbeResponse) GetMaxRepoFormat() uint32 {
	if x != nil {
		return x.MaxRepoFormat
	}
	return 0
}

func (x *ProbeResponse) GetSupportedOperations() []string {
	if x != nil {
		return x.SupportedOperations
	}
	return nil
}

func (x *ProbeResponse) GetWorkDir() string {
	if x != nil && x.WorkDir != nil {
		return *x.WorkDir
	}
	return ""
}

type CommitSelector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Selector:
	//
	//	*CommitSelector_StateIdOrPrefix
	//	*CommitSelector_Branch
	Selector      isCommitSelector_Selector `protobuf_oneof:"selector"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitSelector) Reset() {
	*x = CommitSelector{}
	mi := &file_fvs2d_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitSelector) ProtoMessage() {}

func (x *CommitSelector) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitSelector.ProtoReflect.Descriptor instead.
func (*CommitSelector) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{12}
}

func (x *CommitSelector) GetSelector() isCommitSelector_Selector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *CommitSelector) GetStateIdOrPrefix() string {
	if x != nil {
		if x, ok := x.Selector.(*CommitSelector_StateIdOrPrefix); ok {
			return x.StateIdOrPrefix
		}
	}
	return ""
}

func (x *CommitSelector) GetBranch() string {
	if x != nil {
		if x, ok := x.Selector.(*CommitSelector_Branch); ok {
			return x.Branch
		}
	}
	return ""
}

type isCommitSelector_Selector interface {
	isCommitSelector_Selector()
}

type CommitSelector_StateIdOrPrefix struct {
	StateIdOrPrefix string `protobuf:"bytes,1,opt,name=state_id_or_prefix,json=stateIdOrPrefix,proto3,oneof"`
}

type CommitSelector_Branch struct {
	Branch string `protobuf:"bytes,2,opt,name=branch,proto3,oneof"`
}

func (*CommitSelector_StateIdOrPrefix) isCommitSelector_Selector() {}

func (*CommitSelector_Branch) isCommitSelector_Selector() {}

type Layer struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepositoryPath string                 `protobuf:"bytes,1,opt,name=repository_path,json=repositoryPath,proto3" json:"repository_path,omitempty"`
	Revision       *CommitSelector        `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Layer) Reset() {
	*x = Layer{}
	mi := &file_fvs2d_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Layer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layer) ProtoMessage() {}

func (x *Layer) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layer.ProtoReflect.Descriptor instead.
func (*Layer) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{13}
}

func (x *Layer) GetRepositoryPath() string {
	if x != nil {
		return x.RepositoryPath
	}
	return ""
}

func (x *Layer) GetRevision() *CommitSelector {
	if x != nil {
		return x.Revision
	}
	return nil
}

type MountSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountPoint    string                 `protobuf:"bytes,1,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	Layers        []*Layer               `protobuf:"bytes,2,rep,name=layers,proto3" json:"layers,omitempty"`
	UpperPath     *string                `protobuf:"bytes,3,opt,name=upper_path,json=upperPath,proto3,oneof" json:"upper_path,omitempty"`
	Debug         bool                   `protobuf:"varint,4,opt,name=debug,proto3" json:"debug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountSpec) Reset() {
	*x = MountSpec{}
	mi := &file_fvs2d_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountSpec) ProtoMessage() {}

func (x *MountSpec) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountSpec.ProtoReflect.Descriptor instead.
func (*MountSpec) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{14}
}

func (x *MountSpec) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *MountSpec) GetLayers() []*Layer {
	if x != nil {
		return x.Layers
	}
	return nil
}

func (x *MountSpec) GetUpperPath() string {
	if x != nil && x.UpperPath != nil {
		return *x.UpperPath
	}
	return ""
}

func (x *MountSpec) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

type CreateMountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *MountSpec             `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMountRequest) Reset() {
	*x = CreateMountRequest{}
	mi := &file_fvs2d_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMountRequest) ProtoMessage() {}

func (x *CreateMountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMountRequest.ProtoReflect.Descriptor instead.
func (*CreateMountRequest) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{15}
}

func (x *CreateMountRequest) GetSpec() *MountSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type ResolvedLayer struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepositoryPath string                 `protobuf:"bytes,1,opt,name=repository_path,json=repositoryPath,proto3" json:"repository_path,omitempty"`
	StateId        string                 `protobuf:"bytes,2,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	BlocksPath     string                 `protobuf:"bytes,3,opt,name=blocks_path,json=blocksPath,proto3" json:"blocks_path,omitempty"`
	BlockSize      uint32                 `protobuf:"varint,4,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolvedLayer) Reset() {
	*x = ResolvedLayer{}
	mi := &file_fvs2d_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedLayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedLayer) ProtoMessage() {}

func (x *ResolvedLayer) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedLayer.ProtoReflect.Descriptor instead.
func (*ResolvedLayer) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{16}
}

func (x *ResolvedLayer) GetRepositoryPath() string {
	if x != nil {
		return x.RepositoryPath
	}
	return ""
}

func (x *ResolvedLayer) GetStateId() string {
	if x != nil {
		return x.StateId
	}
	return ""
}

func (x *ResolvedLayer) GetBlocksPath() string {
	if x != nil {
		return x.BlocksPath
	}
	return ""
}

func (x *ResolvedLayer) GetBlockSize() uint32 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

type Mount struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Spec           *MountSpec             `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	ResolvedLayers []*ResolvedLayer       `protobuf:"bytes,3,rep,name=resolved_layers,json=resolvedLayers,proto3" json:"resolved_layers,omitempty"`
	NodeCount      uint64                 `protobuf:"varint,4,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	MountedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=mounted_at,json=mountedAt,proto3" json:"mounted_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Mount) Reset() {
	*x = Mount{}
	mi := &file_fvs2d_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mount) ProtoMessage() {}

func (x *Mount) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mount.ProtoReflect.Descriptor instead.
func (*Mount) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{17}
}

func (x *Mount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Mount) GetSpec() *MountSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Mount) GetResolvedLayers() []*ResolvedLayer {
	if x != nil {
		return x.ResolvedLayers
	}
	return nil
}

func (x *Mount) GetNodeCount() uint64 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *Mount) GetMountedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MountedAt
	}
	return nil
}

type GetMountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountId       string                 `protobuf:"bytes,1,opt,name=mount_id,json=mountId,proto3" json:"mount_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMountRequest) Reset() {
	*x = GetMountRequest{}
	mi := &file_fvs2d_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMountRequest) ProtoMessage() {}

func (x *GetMountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMountRequest.ProtoReflect.Descriptor instead.
func (*GetMountRequest) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{18}
}

func (x *GetMountRequest) GetMountId() string {
	if x != nil {
		return x.MountId
	}
	return ""
}

type ListMountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mounts        []*Mount               `protobuf:"bytes,1,rep,name=mounts,proto3" json:"mounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMountsResponse) Reset() {
	*x = ListMountsResponse{}
	mi := &file_fvs2d_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMountsResponse) ProtoMessage() {}

func (x *ListMountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMountsResponse.ProtoReflect.Descriptor instead.
func (*ListMountsResponse) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{19}
}

func (x *ListMountsResponse) GetMounts() []*Mount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

type UnmountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountId       string                 `protobuf:"bytes,1,opt,name=mount_id,json=mountId,proto3" json:"mount_id,omitempty"`
	Mode          UnmountMode            `protobuf:"varint,2,opt,name=mode,proto3,enum=fvs2d.v1.UnmountMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmountRequest) Reset() {
	*x = UnmountRequest{}
	mi := &file_fvs2d_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountRequest) ProtoMessage() {}

func (x *UnmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountRequest.ProtoReflect.Descriptor instead.
func (*UnmountRequest) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{20}
}

func (x *UnmountRequest) GetMountId() string {
	if x != nil {
		return x.MountId
	}
	return ""
}

func (x *UnmountRequest) GetMode() UnmountMode {
	if x != nil {
		return x.Mode
	}
	return UnmountMode_UNMOUNT_MODE_NORMAL
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          UnmountMode            `protobuf:"varint,1,opt,name=mode,proto3,enum=fvs2d.v1.UnmountMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_fvs2d_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{21}
}

func (x *ShutdownRequest) GetMode() UnmountMode {
	if x != nil {
		return x.Mode
	}
	return UnmountMode_UNMOUNT_MODE_NORMAL
}

type ListFilesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepositoryPath string                 `protobuf:"bytes,1,opt,name=repository_path,json=repositoryPath,proto3" json:"repository_path,omitempty"`
	Revision       *CommitSelector        `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_fvs2d_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{22}
}

func (x *ListFilesRequest) GetRepositoryPath() string {
	if x != nil {
		return x.RepositoryPath
	}
	return ""
}

func (x *ListFilesRequest) GetRevision() *CommitSelector {
	if x != nil {
		return x.Revision
	}
	return nil
}

type FileInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode  uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Size  int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// link is the symlink target, empty for regular files.
	Link          string `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_fvs2d_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{23}
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInfo            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_fvs2d_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{24}
}

func (x *ListFilesResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

type GetFileRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepositoryPath string                 `protobuf:"bytes,1,opt,name=repository_path,json=repositoryPath,proto3" json:"repository_path,omitempty"`
	Revision       *CommitSelector        `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Path           string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// chunk_size caps each streamed chunk's byte length (default chosen by
	// the server when unset or <= 0).
	ChunkSize     int32 `protobuf:"varint,4,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_fvs2d_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{25}
}

func (x *GetFileRequest) GetRepositoryPath() string {
	if x != nil {
		return x.RepositoryPath
	}
	return ""
}

func (x *GetFileRequest) GetRevision() *CommitSelector {
	if x != nil {
		return x.Revision
	}
	return nil
}

func (x *GetFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetFileRequest) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

type GetFileChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Data  []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// offset is the byte offset of data[0] within the file.
	Offset        int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileChunk) Reset() {
	*x = GetFileChunk{}
	mi := &file_fvs2d_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileChunk) ProtoMessage() {}

func (x *GetFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileChunk.ProtoReflect.Descriptor instead.
func (*GetFileChunk) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{26}
}

func (x *GetFileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetFileChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type DiffRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepositoryPath string                 `protobuf:"bytes,1,opt,name=repository_path,json=repositoryPath,proto3" json:"repository_path,omitempty"`
	FromState      string                 `protobuf:"bytes,2,opt,name=from_state,json=fromState,proto3" json:"from_state,omitempty"`
	ToState        string                 `protobuf:"bytes,3,opt,name=to_state,json=toState,proto3" json:"to_state,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DiffRequest) Reset() {
	*x = DiffRequest{}
	mi := &file_fvs2d_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffRequest) ProtoMessage() {}

func (x *DiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffRequest.ProtoReflect.Descriptor instead.
func (*DiffRequest) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{27}
}

func (x *DiffRequest) GetRepositoryPath() string {
	if x != nil {
		return x.RepositoryPath
	}
	return ""
}

func (x *DiffRequest) GetFromState() string {
	if x != nil {
		return x.FromState
	}
	return ""
}

func (x *DiffRequest) GetToState() string {
	if x != nil {
		return x.ToState
	}
	return ""
}

type DiffMountRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	MountId string                 `protobuf:"bytes,1,opt,name=mount_id,json=mountId,proto3" json:"mount_id,omitempty"`
	// prune_unchanged removes upper entries identical to the resolved lower.
	PruneUnchanged bool `protobuf:"varint,2,opt,name=prune_unchanged,json=pruneUnchanged,proto3" json:"prune_unchanged,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DiffMountRequest) Reset() {
	*x = DiffMountRequest{}
	mi := &file_fvs2d_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffMountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffMountRequest) ProtoMessage() {}

func (x *DiffMountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffMountRequest.ProtoReflect.Descriptor instead.
func (*DiffMountRequest) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{28}
}

func (x *DiffMountRequest) GetMountId() string {
	if x != nil {
		return x.MountId
	}
	return ""
}

func (x *DiffMountRequest) GetPruneUnchanged() bool {
	if x != nil {
		return x.PruneUnchanged
	}
	return false
}

type FileChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Kind  ChangeKind             `protobuf:"varint,2,opt,name=kind,proto3,enum=fvs2d.v1.ChangeKind" json:"kind,omitempty"`
	// size_delta is to_size - from_size (0 for pure metadata/mode changes,
	// from_size for a removal, to_size for an addition).
	SizeDelta     int64 `protobuf:"varint,3,opt,name=size_delta,json=sizeDelta,proto3" json:"size_delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChange) Reset() {
	*x = FileChange{}
	mi := &file_fvs2d_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChange) ProtoMessage() {}

func (x *FileChange) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChange.ProtoReflect.Descriptor instead.
func (*FileChange) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{29}
}

func (x *FileChange) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileChange) GetKind() ChangeKind {
	if x != nil {
		return x.Kind
	}
	return ChangeKind_CHANGE_KIND_UNSPECIFIED
}

func (x *FileChange) GetSizeDelta() int64 {
	if x != nil {
		return x.SizeDelta
	}
	return 0
}

type DiffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changes       []*FileChange          `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffResponse) Reset() {
	*x = DiffResponse{}
	mi := &file_fvs2d_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffResponse) ProtoMessage() {}

func (x *DiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffResponse.ProtoReflect.Descriptor instead.
func (*DiffResponse) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{30}
}

func (x *DiffResponse) GetChanges() []*FileChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

var File_fvs2d_proto protoreflect.FileDescriptor

const file_fvs2d_proto_rawDesc = "" +
	"\n" +
	"\vfvs2d.proto\x12\bfvs2d.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"y\n" +
	"\x12ListCommitsRequest\x12'\n" +
	"\x0frepository_path\x18\x01 \x01(\tR\x0erepositoryPath\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"v\n" +
	"\x13ListCommitsResponse\x121\n" +
	"\acommits\x18\x02 \x03(\v2\x17.fvs2d.v1.CommitSummaryR\acommits\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageTokenJ\x04\b\x01\x10\x02\"h\n" +
	"\x10GetCommitRequest\x12'\n" +
	"\x0frepository_path\x18\x01 \x01(\tR\x0erepositoryPath\x12+\n" +
	"\x12state_id_or_prefix\x18\x02 \x01(\tR\x0fstateIdOrPrefix\"\xd7\x01\n" +
	"\x0eRestoreRequest\x12'\n" +
	"\x0frepository_path\x18\x01 \x01(\tR\x0erepositoryPath\x12+\n" +
	"\x12state_id_or_prefix\x18\x02 \x01(\tR\x0fstateIdOrPrefix\x12.\n" +
	"\x10destination_path\x18\x03 \x01(\tH\x00R\x0fdestinationPath\x88\x01\x01\x12\x14\n" +
	"\x05clean\x18\x04 \x01(\bR\x05clean\x12\x14\n" +
	"\x05reset\x18\x05 \x01(\bR\x05resetB\x13\n" +
	"\x11_destination_path\"W\n" +
	"\x0fRestoreResponse\x12\x19\n" +
	"\bstate_id\x18\x01 \x01(\tR\astateId\x12)\n" +
	"\x10destination_path\x18\x02 \x01(\tR\x0fdestinationPath\"_\n" +
	"\x15InitRepositoryRequest\x12'\n" +
	"\x0frepository_path\x18\x01 \x01(\tR\x0erepositoryPath\x12\x1d\n" +
	"\n" +
	"block_size\x18\x02 \x01(\rR\tblockSize\"T\n" +
	"\n" +
	"Repository\x12'\n" +
	"\x0frepository_path\x18\x01 \x01(\tR\x0erepositoryPath\x12\x1d\n" +
	"\n" +
	"block_size\x18\x02 \x01(\rR\tblockSize\"s\n" +
	"\rCommitRequest\x12'\n" +
	"\x0frepository_path\x18\x01 \x01(\tR\x0erepositoryPath\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vallow_empty\x18\x03 \x01(\bR\n" +
	"allowEmpty\"\xda\x01\n" +
	"\x06Commit\x12'\n" +
	"\x0frepository_path\x18\x01 \x01(\tR\x0erepositoryPath\x12\x19\n" +
	"\bstate_id\x18\x02 \x01(\tR\astateId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"file_count\x18\x04 \x01(\x04R\tfileCount\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x18\n" +
	"\acreated\x18\x06 \x01(\bR\acreated\"\xc7\x01\n" +
	"\rCommitSummary\x12'\n" +
	"\x0frepository_path\x18\x01 \x01(\tR\x0erepositoryPath\x12\x19\n" +
	"\bstate_id\x18\x02 \x01(\tR\astateId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"file_count\x18\x05 \x01(\x04R\tfileCount\"\xf7\x01\n" +
	"\bProgress\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12\x18\n" +
	"\acurrent\x18\x02 \x01(\x03R\acurrent\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x12\n" +
	"\x04done\x18\x05 \x01(\bR\x04done\x125\n" +
	"\rresult_commit\x18\x06 \x01(\v2\x10.fvs2d.v1.CommitR\fresultCommit\x12@\n" +
	"\x0eresult_restore\x18\a \x01(\v2\x19.fvs2d.v1.RestoreResponseR\rresultRestore\"\x9b\x04\n" +
	"\rProbeResponse\x12%\n" +
	"\x0edaemon_version\x18\x01 \x01(\tR\rdaemonVersion\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x124\n" +
	"\x16fuse_backend_available\x18\x04 \x01(\bR\x14fuseBackendAvailable\x12.\n" +
	"\x13dev_fuse_accessible\x18\x05 \x01(\bR\x11devFuseAccessible\x121\n" +
	"\x14fusermount_available\x18\x06 \x01(\bR\x13fusermountAvailable\x12,\n" +
	"\x12running_in_flatpak\x18\a \x01(\bR\x10runningInFlatpak\x12\x1f\n" +
	"\vapi_version\x18\b \x01(\tR\n" +
	"apiVersion\x12&\n" +
	"\x0fmin_repo_format\x18\t \x01(\rR\rminRepoFormat\x12&\n" +
	"\x0fmax_repo_format\x18\n" +
	" \x01(\rR\rmaxRepoFormat\x121\n" +
	"\x14supported_operations\x18\v \x03(\tR\x13supportedOperations\x12\x1e\n" +
	"\bwork_dir\x18\f \x01(\tH\x00R\aworkDir\x88\x01\x01B\v\n" +
	"\t_work_dir\"e\n" +
	"\x0eCommitSelector\x12-\n" +
	"\x12state_id_or_prefix\x18\x01 \x01(\tH\x00R\x0fstateIdOrPrefix\x12\x18\n" +
	"\x06branch\x18\x02 \x01(\tH\x00R\x06branchB\n" +
	"\n" +
	"\bselector\"f\n" +
	"\x05Layer\x12'\n" +
	"\x0frepository_path\x18\x01 \x01(\tR\x0erepositoryPath\x124\n" +
	"\brevision\x18\x02 \x01(\v2\x18.fvs2d.v1.CommitSelectorR\brevision\"\x9e\x01\n" +
	"\tMountSpec\x12\x1f\n" +
	"\vmount_point\x18\x01 \x01(\tR\n" +
	"mountPoint\x12'\n" +
	"\x06layers\x18\x02 \x03(\v2\x0f.fvs2d.v1.LayerR\x06layers\x12\"\n" +
	"\n" +
	"upper_path\x18\x03 \x01(\tH\x00R\tupperPath\x88\x01\x01\x12\x14\n" +
	"\x05debug\x18\x04 \x01(\bR\x05debugB\r\n" +
	"\v_upper_path\"=\n" +
	"\x12CreateMountRequest\x12'\n" +
	"\x04spec\x18\x01 \x01(\v2\x13.fvs2d.v1.MountSpecR\x04spec\"\x93\x01\n" +
	"\rResolvedLayer\x12'\n" +
	"\x0frepository_path\x18\x01 \x01(\tR\x0erepositoryPath\x12\x19\n" +
	"\bstate_id\x18\x02 \x01(\tR\astateId\x12\x1f\n" +
	"\vblocks_path\x18\x03 \x01(\tR\n" +
	"blocksPath\x12\x1d\n" +
	"\n" +
	"block_size\x18\x04 \x01(\rR\tblockSize\"\xdc\x01\n" +
	"\x05Mount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x04spec\x18\x02 \x01(\v2\x13.fvs2d.v1.MountSpecR\x04spec\x12@\n" +
	"\x0fresolved_layers\x18\x03 \x03(\v2\x17.fvs2d.v1.ResolvedLayerR\x0eresolvedLayers\x12\x1d\n" +
	"\n" +
	"node_count\x18\x04 \x01(\x04R\tnodeCount\x129\n" +
	"\n" +
	"mounted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tmountedAt\",\n" +
	"\x0fGetMountRequest\x12\x19\n" +
	"\bmount_id\x18\x01 \x01(\tR\amountId\"=\n" +
	"\x12ListMountsResponse\x12'\n" +
	"\x06mounts\x18\x01 \x03(\v2\x0f.fvs2d.v1.MountR\x06mounts\"V\n" +
	"\x0eUnmountRequest\x12\x19\n" +
	"\bmount_id\x18\x01 \x01(\tR\amountId\x12)\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x15.fvs2d.v1.UnmountModeR\x04mode\"<\n" +
	"\x0fShutdownRequest\x12)\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x15.fvs2d.v1.UnmountModeR\x04mode\"q\n" +
	"\x10ListFilesRequest\x12'\n" +
	"\x0frepository_path\x18\x01 \x01(\tR\x0erepositoryPath\x124\n" +
	"\brevision\x18\x02 \x01(\v2\x18.fvs2d.v1.CommitSelectorR\brevision\"Z\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04link\x18\x04 \x01(\tR\x04link\"=\n" +
	"\x11ListFilesResponse\x12(\n" +
	"\x05files\x18\x01 \x03(\v2\x12.fvs2d.v1.FileInfoR\x05files\"\xa2\x01\n" +
	"\x0eGetFileRequest\x12'\n" +
	"\x0frepository_path\x18\x01 \x01(\tR\x0erepositoryPath\x124\n" +
	"\brevision\x18\x02 \x01(\v2\x18.fvs2d.v1.CommitSelectorR\brevision\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x04 \x01(\x05R\tchunkSize\":\n" +
	"\fGetFileChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"p\n" +
	"\vDiffRequest\x12'\n" +
	"\x0frepository_path\x18\x01 \x01(\tR\x0erepositoryPath\x12\x1d\n" +
	"\n" +
	"from_state\x18\x02 \x01(\tR\tfromState\x12\x19\n" +
	"\bto_state\x18\x03 \x01(\tR\atoState\"V\n" +
	"\x10DiffMountRequest\x12\x19\n" +
	"\bmount_id\x18\x01 \x01(\tR\amountId\x12'\n" +
	"\x0fprune_unchanged\x18\x02 \x01(\bR\x0epruneUnchanged\"i\n" +
	"\n" +
	"FileChange\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12(\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x14.fvs2d.v1.ChangeKindR\x04kind\x12\x1d\n" +
	"\n" +
	"size_delta\x18\x03 \x01(\x03R\tsizeDelta\">\n" +
	"\fDiffResponse\x12.\n" +
	"\achanges\x18\x01 \x03(\v2\x14.fvs2d.v1.FileChangeR\achanges*=\n" +
	"\vUnmountMode\x12\x17\n" +
	"\x13UNMOUNT_MODE_NORMAL\x10\x00\x12\x15\n" +
	"\x11UNMOUNT_MODE_LAZY\x10\x01*s\n" +
	"\n" +
	"ChangeKind\x12\x1b\n" +
	"\x17CHANGE_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CHANGE_KIND_ADDED\x10\x01\x12\x18\n" +
	"\x14CHANGE_KIND_MODIFIED\x10\x02\x12\x17\n" +
	"\x13CHANGE_KIND_REMOVED\x10\x032\xb9\b\n" +
	"\x05Fvs2d\x128\n" +
	"\x05Probe\x12\x16.google.protobuf.Empty\x1a\x17.fvs2d.v1.ProbeResponse\x12G\n" +
	"\x0eInitRepository\x12\x1f.fvs2d.v1.InitRepositoryRequest\x1a\x14.fvs2d.v1.Repository\x123\n" +
	"\x06Commit\x12\x17.fvs2d.v1.CommitRequest\x1a\x10.fvs2d.v1.Commit\x12=\n" +
	"\fCommitStream\x12\x17.fvs2d.v1.CommitRequest\x1a\x12.fvs2d.v1.Progress0\x01\x12J\n" +
	"\vListCommits\x12\x1c.fvs2d.v1.ListCommitsRequest\x1a\x1d.fvs2d.v1.ListCommitsResponse\x129\n" +
	"\tGetCommit\x12\x1a.fvs2d.v1.GetCommitRequest\x1a\x10.fvs2d.v1.Commit\x12>\n" +
	"\aRestore\x12\x18.fvs2d.v1.RestoreRequest\x1a\x19.fvs2d.v1.RestoreResponse\x12?\n" +
	"\rRestoreStream\x12\x18.fvs2d.v1.RestoreRequest\x1a\x12.fvs2d.v1.Progress0\x01\x12D\n" +
	"\tListFiles\x12\x1a.fvs2d.v1.ListFilesRequest\x1a\x1b.fvs2d.v1.ListFilesResponse\x12=\n" +
	"\aGetFile\x12\x18.fvs2d.v1.GetFileRequest\x1a\x16.fvs2d.v1.GetFileChunk0\x01\x125\n" +
	"\x04Diff\x12\x15.fvs2d.v1.DiffRequest\x1a\x16.fvs2d.v1.DiffResponse\x12?\n" +
	"\tDiffMount\x12\x1a.fvs2d.v1.DiffMountRequest\x1a\x16.fvs2d.v1.DiffResponse\x12<\n" +
	"\vCreateMount\x12\x1c.fvs2d.v1.CreateMountRequest\x1a\x0f.fvs2d.v1.Mount\x126\n" +
	"\bGetMount\x12\x19.fvs2d.v1.GetMountRequest\x1a\x0f.fvs2d.v1.Mount\x12B\n" +
	"\n" +
	"ListMounts\x12\x16.google.protobuf.Empty\x1a\x1c.fvs2d.v1.ListMountsResponse\x12;\n" +
	"\aUnmount\x12\x18.fvs2d.v1.UnmountRequest\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\bShutdown\x12\x19.fvs2d.v1.ShutdownRequest\x1a\x16.google.protobuf.EmptyB\x17Z\x15fvs2d/fvs2dpb;fvs2dpbb\x06proto3"

var (
	file_fvs2d_proto_rawDescOnce sync.Once
	file_fvs2d_proto_rawDescData []byte
)

func file_fvs2d_proto_rawDescGZIP() []byte {
	file_fvs2d_proto_rawDescOnce.Do(func() {
		file_fvs2d_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fvs2d_proto_rawDesc), len(file_fvs2d_proto_rawDesc)))
	})
	return file_fvs2d_proto_rawDescData
}

var file_fvs2d_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_fvs2d_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_fvs2d_proto_goTypes = []any{
	(UnmountMode)(0),              // 0: fvs2d.v1.UnmountMode
	(ChangeKind)(0),               // 1: fvs2d.v1.ChangeKind
	(*ListCommitsRequest)(nil),    // 2: fvs2d.v1.ListCommitsRequest
	(*ListCommitsResponse)(nil),   // 3: fvs2d.v1.ListCommitsResponse
	(*GetCommitRequest)(nil),      // 4: fvs2d.v1.GetCommitRequest
	(*RestoreRequest)(nil),        // 5: fvs2d.v1.RestoreRequest
	(*RestoreResponse)(nil),       // 6: fvs2d.v1.RestoreResponse
	(*InitRepositoryRequest)(nil), // 7: fvs2d.v1.InitRepositoryRequest
	(*Repository)(nil),            // 8: fvs2d.v1.Repository
	(*CommitRequest)(nil),         // 9: fvs2d.v1.CommitRequest
	(*Commit)(nil),                // 10: fvs2d.v1.Commit
	(*CommitSummary)(nil),         // 11: fvs2d.v1.CommitSummary
	(*Progress)(nil),              // 12: fvs2d.v1.Progress
	(*ProbeResponse)(nil),         // 13: fvs2d.v1.ProbeResponse
	(*CommitSelector)(nil),        // 14: fvs2d.v1.CommitSelector
	(*Layer)(nil),                 // 15: fvs2d.v1.Layer
	(*MountSpec)(nil),             // 16: fvs2d.v1.MountSpec
	(*CreateMountRequest)(nil),    // 17: fvs2d.v1.CreateMountRequest
	(*ResolvedLayer)(nil),         // 18: fvs2d.v1.ResolvedLayer
	(*Mount)(nil),                 // 19: fvs2d.v1.Mount
	(*GetMountRequest)(nil),       // 20: fvs2d.v1.GetMountRequest
	(*ListMountsResponse)(nil),    // 21: fvs2d.v1.ListMountsResponse
	(*UnmountRequest)(nil),        // 22: fvs2d.v1.UnmountRequest
	(*ShutdownRequest)(nil),       // 23: fvs2d.v1.ShutdownRequest
	(*ListFilesRequest)(nil),      // 24: fvs2d.v1.ListFilesRequest
	(*FileInfo)(nil),              // 25: fvs2d.v1.FileInfo
	(*ListFilesResponse)(nil),     // 26: fvs2d.v1.ListFilesResponse
	(*GetFileRequest)(nil),        // 27: fvs2d.v1.GetFileRequest
	(*GetFileChunk)(nil),          // 28: fvs2d.v1.GetFileChunk
	(*DiffRequest)(nil),           // 29: fvs2d.v1.DiffRequest
	(*DiffMountRequest)(nil),      // 30: fvs2d.v1.DiffMountRequest
	(*FileChange)(nil),            // 31: fvs2d.v1.FileChange
	(*DiffResponse)(nil),          // 32: fvs2d.v1.DiffResponse
	(*timestamppb.Timestamp)(nil), // 33: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 34: google.protobuf.Empty
}
var file_fvs2d_proto_depIdxs = []int32{
	11, // 0: fvs2d.v1.ListCommitsResponse.commits:type_name -> fvs2d.v1.CommitSummary
	33, // 1: fvs2d.v1.Commit.created_at:type_name -> google.protobuf.Timestamp
	33, // 2: fvs2d.v1.CommitSummary.created_at:type_name -> google.protobuf.Timestamp
	10, // 3: fvs2d.v1.Progress.result_commit:type_name -> fvs2d.v1.Commit
	6,  // 4: fvs2d.v1.Progress.result_restore:type_name -> fvs2d.v1.RestoreResponse
	33, // 5: fvs2d.v1.ProbeResponse.started_at:type_name -> google.protobuf.Timestamp
	14, // 6: fvs2d.v1.Layer.revision:type_name -> fvs2d.v1.CommitSelector
	15, // 7: fvs2d.v1.MountSpec.layers:type_name -> fvs2d.v1.Layer
	16, // 8: fvs2d.v1.CreateMountRequest.spec:type_name -> fvs2d.v1.MountSpec
	16, // 9: fvs2d.v1.Mount.spec:type_name -> fvs2d.v1.MountSpec
	18, // 10: fvs2d.v1.Mount.resolved_layers:type_name -> fvs2d.v1.ResolvedLayer
	33, // 11: fvs2d.v1.Mount.mounted_at:type_name -> google.protobuf.Timestamp
	19, // 12: fvs2d.v1.ListMountsResponse.mounts:type_name -> fvs2d.v1.Mount
	0,  // 13: fvs2d.v1.UnmountRequest.mode:type_name -> fvs2d.v1.UnmountMode
	0,  // 14: fvs2d.v1.ShutdownRequest.mode:type_name -> fvs2d.v1.UnmountMode
	14, // 15: fvs2d.v1.ListFilesRequest.revision:type_name -> fvs2d.v1.CommitSelector
	25, // 16: fvs2d.v1.ListFilesResponse.files:type_name -> fvs2d.v1.FileInfo
	14, // 17: fvs2d.v1.GetFileRequest.revision:type_name -> fvs2d.v1.CommitSelector
	1,  // 18: fvs2d.v1.FileChange.kind:type_name -> fvs2d.v1.ChangeKind
	31, // 19: fvs2d.v1.DiffResponse.changes:type_name -> fvs2d.v1.FileChange
	34, // 20: fvs2d.v1.Fvs2d.Probe:input_type -> google.protobuf.Empty
	7,  // 21: fvs2d.v1.Fvs2d.InitRepository:input_type -> fvs2d.v1.InitRepositoryRequest
	9,  // 22: fvs2d.v1.Fvs2d.Commit:input_type -> fvs2d.v1.CommitRequest
	9,  // 23: fvs2d.v1.Fvs2d.CommitStream:input_type -> fvs2d.v1.CommitRequest
	2,  // 24: fvs2d.v1.Fvs2d.ListCommits:input_type -> fvs2d.v1.ListCommitsRequest
	4,  // 25: fvs2d.v1.Fvs2d.GetCommit:input_type -> fvs2d.v1.GetCommitRequest
	5,  // 26: fvs2d.v1.Fvs2d.Restore:input_type -> fvs2d.v1.RestoreRequest
	5,  // 27: fvs2d.v1.Fvs2d.RestoreStream:input_type -> fvs2d.v1.RestoreRequest
	24, // 28: fvs2d.v1.Fvs2d.ListFiles:input_type -> fvs2d.v1.ListFilesRequest
	27, // 29: fvs2d.v1.Fvs2d.GetFile:input_type -> fvs2d.v1.GetFileRequest
	29, // 30: fvs2d.v1.Fvs2d.Diff:input_type -> fvs2d.v1.DiffRequest
	30, // 31: fvs2d.v1.Fvs2d.DiffMount:input_type -> fvs2d.v1.DiffMountRequest
	17, // 32: fvs2d.v1.Fvs2d.CreateMount:input_type -> fvs2d.v1.CreateMountRequest
	20, // 33: fvs2d.v1.Fvs2d.GetMount:input_type -> fvs2d.v1.GetMountRequest
	34, // 34: fvs2d.v1.Fvs2d.ListMounts:input_type -> google.protobuf.Empty
	22, // 35: fvs2d.v1.Fvs2d.Unmount:input_type -> fvs2d.v1.UnmountRequest
	23, // 36: fvs2d.v1.Fvs2d.Shutdown:input_type -> fvs2d.v1.ShutdownRequest
	13, // 37: fvs2d.v1.Fvs2d.Probe:output_type -> fvs2d.v1.ProbeResponse
	8,  // 38: fvs2d.v1.Fvs2d.InitRepository:output_type -> fvs2d.v1.Repository
	10, // 39: fvs2d.v1.Fvs2d.Commit:output_type -> fvs2d.v1.Commit
	12, // 40: fvs2d.v1.Fvs2d.CommitStream:output_type -> fvs2d.v1.Progress
	3,  // 41: fvs2d.v1.Fvs2d.ListCommits:output_type -> fvs2d.v1.ListCommitsResponse
	10, // 42: fvs2d.v1.Fvs2d.GetCommit:output_type -> fvs2d.v1.Commit
	6,  // 43: fvs2d.v1.Fvs2d.Restore:output_type -> fvs2d.v1.RestoreResponse
	12, // 44: fvs2d.v1.Fvs2d.RestoreStream:output_type -> fvs2d.v1.Progress
	26, // 45: fvs2d.v1.Fvs2d.ListFiles:output_type -> fvs2d.v1.ListFilesResponse
	28, // 46: fvs2d.v1.Fvs2d.GetFile:output_type -> fvs2d.v1.GetFileChunk
	32, // 47: fvs2d.v1.Fvs2d.Diff:output_type -> fvs2d.v1.DiffResponse
	32, // 48: fvs2d.v1.Fvs2d.DiffMount:output_type -> fvs2d.v1.DiffResponse
	19, // 49: fvs2d.v1.Fvs2d.CreateMount:output_type -> fvs2d.v1.Mount
	19, // 50: fvs2d.v1.Fvs2d.GetMount:output_type -> fvs2d.v1.Mount
	21, // 51: fvs2d.v1.Fvs2d.ListMounts:output_type -> fvs2d.v1.ListMountsResponse
	34, // 52: fvs2d.v1.Fvs2d.Unmount:output_type -> google.protobuf.Empty
	34, // 53: fvs2d.v1.Fvs2d.Shutdown:output_type -> google.protobuf.Empty
	37, // [37:54] is the sub-list for method output_type
	20, // [20:37] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_fvs2d_proto_init() }
func file_fvs2d_proto_init() {
	if File_fvs2d_proto != nil {
		return
	}
	file_fvs2d_proto_msgTypes[3].OneofWrappers = []any{}
	file_fvs2d_proto_msgTypes[11].OneofWrappers = []any{}
	file_fvs2d_proto_msgTypes[12].OneofWrappers = []any{
		(*CommitSelector_StateIdOrPrefix)(nil),
		(*CommitSelector_Branch)(nil),
	}
	file_fvs2d_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fvs2d_proto_rawDesc), len(file_fvs2d_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fvs2d_proto_goTypes,
		DependencyIndexes: file_fvs2d_proto_depIdxs,
		EnumInfos:         file_fvs2d_proto_enumTypes,
		MessageInfos:      file_fvs2d_proto_msgTypes,
	}.Build()
	File_fvs2d_proto = out.File
	file_fvs2d_proto_goTypes = nil
	file_fvs2d_proto_depIdxs = nil
}
