// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: fvs2d.proto

// v1 compatibility policy: fields and messages are additive within v1;
// existing field numbers/names are never reused. A field or message that is
// renamed or removed must have its old number/name added to a `reserved`
// declaration in the same change.

package fvs2dpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Fvs2D_Probe_FullMethodName          = "/fvs2d.v1.Fvs2d/Probe"
	Fvs2D_InitRepository_FullMethodName = "/fvs2d.v1.Fvs2d/InitRepository"
	Fvs2D_Commit_FullMethodName         = "/fvs2d.v1.Fvs2d/Commit"
	Fvs2D_CommitStream_FullMethodName   = "/fvs2d.v1.Fvs2d/CommitStream"
	Fvs2D_ListCommits_FullMethodName    = "/fvs2d.v1.Fvs2d/ListCommits"
	Fvs2D_GetCommit_FullMethodName      = "/fvs2d.v1.Fvs2d/GetCommit"
	Fvs2D_Restore_FullMethodName        = "/fvs2d.v1.Fvs2d/Restore"
	Fvs2D_RestoreStream_FullMethodName  = "/fvs2d.v1.Fvs2d/RestoreStream"
	Fvs2D_ListFiles_FullMethodName      = "/fvs2d.v1.Fvs2d/ListFiles"
	Fvs2D_GetFile_FullMethodName        = "/fvs2d.v1.Fvs2d/GetFile"
	Fvs2D_Diff_FullMethodName           = "/fvs2d.v1.Fvs2d/Diff"
	Fvs2D_CreateMount_FullMethodName    = "/fvs2d.v1.Fvs2d/CreateMount"
	Fvs2D_GetMount_FullMethodName       = "/fvs2d.v1.Fvs2d/GetMount"
	Fvs2D_ListMounts_FullMethodName     = "/fvs2d.v1.Fvs2d/ListMounts"
	Fvs2D_Unmount_FullMethodName        = "/fvs2d.v1.Fvs2d/Unmount"
	Fvs2D_Shutdown_FullMethodName       = "/fvs2d.v1.Fvs2d/Shutdown"
)

// Fvs2DClient is the client API for Fvs2D service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Fvs2DClient interface {
	Probe(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ProbeResponse, error)
	InitRepository(ctx context.Context, in *InitRepositoryRequest, opts ...grpc.CallOption) (*Repository, error)
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*Commit, error)
	CommitStream(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Progress], error)
	ListCommits(ctx context.Context, in *ListCommitsRequest, opts ...grpc.CallOption) (*ListCommitsResponse, error)
	GetCommit(ctx context.Context, in *GetCommitRequest, opts ...grpc.CallOption) (*Commit, error)
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error)
	RestoreStream(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Progress], error)
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetFileChunk], error)
	Diff(ctx context.Context, in *DiffRequest, opts ...grpc.CallOption) (*DiffResponse, error)
	CreateMount(ctx context.Context, in *CreateMountRequest, opts ...grpc.CallOption) (*Mount, error)
	GetMount(ctx context.Context, in *GetMountRequest, opts ...grpc.CallOption) (*Mount, error)
	ListMounts(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListMountsResponse, error)
	Unmount(ctx context.Context, in *UnmountRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type fvs2DClient struct {
	cc grpc.ClientConnInterface
}

func NewFvs2DClient(cc grpc.ClientConnInterface) Fvs2DClient {
	return &fvs2DClient{cc}
}

func (c *fvs2DClient) Probe(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ProbeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbeResponse)
	err := c.cc.Invoke(ctx, Fvs2D_Probe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvs2DClient) InitRepository(ctx context.Context, in *InitRepositoryRequest, opts ...grpc.CallOption) (*Repository, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Repository)
	err := c.cc.Invoke(ctx, Fvs2D_InitRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvs2DClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*Commit, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Commit)
	err := c.cc.Invoke(ctx, Fvs2D_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvs2DClient) CommitStream(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Progress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Fvs2D_ServiceDesc.Streams[0], Fvs2D_CommitStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CommitRequest, Progress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Fvs2D_CommitStreamClient = grpc.ServerStreamingClient[Progress]

func (c *fvs2DClient) ListCommits(ctx context.Context, in *ListCommitsRequest, opts ...grpc.CallOption) (*ListCommitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommitsResponse)
	err := c.cc.Invoke(ctx, Fvs2D_ListCommits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvs2DClient) GetCommit(ctx context.Context, in *GetCommitRequest, opts ...grpc.CallOption) (*Commit, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Commit)
	err := c.cc.Invoke(ctx, Fvs2D_GetCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvs2DClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreResponse)
	err := c.cc.Invoke(ctx, Fvs2D_Restore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvs2DClient) RestoreStream(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Progress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Fvs2D_ServiceDesc.Streams[1], Fvs2D_RestoreStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RestoreRequest, Progress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Fvs2D_RestoreStreamClient = grpc.ServerStreamingClient[Progress]

func (c *fvs2DClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, Fvs2D_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvs2DClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetFileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Fvs2D_ServiceDesc.Streams[2], Fvs2D_GetFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetFileRequest, GetFileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Fvs2D_GetFileClient = grpc.ServerStreamingClient[GetFileChunk]

func (c *fvs2DClient) Diff(ctx context.Context, in *DiffRequest, opts ...grpc.CallOption) (*DiffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiffResponse)
	err := c.cc.Invoke(ctx, Fvs2D_Diff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvs2DClient) CreateMount(ctx context.Context, in *CreateMountRequest, opts ...grpc.CallOption) (*Mount, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Mount)
	err := c.cc.Invoke(ctx, Fvs2D_CreateMount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvs2DClient) GetMount(ctx context.Context, in *GetMountRequest, opts ...grpc.CallOption) (*Mount, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Mount)
	err := c.cc.Invoke(ctx, Fvs2D_GetMount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvs2DClient) ListMounts(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListMountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMountsResponse)
	err := c.cc.Invoke(ctx, Fvs2D_ListMounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvs2DClient) Unmount(ctx context.Context, in *UnmountRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Fvs2D_Unmount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvs2DClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Fvs2D_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Fvs2DServer is the server API for Fvs2D service.
// All implementations must embed UnimplementedFvs2DServer
// for forward compatibility.
type Fvs2DServer interface {
	Probe(context.Context, *emptypb.Empty) (*ProbeResponse, error)
	InitRepository(context.Context, *InitRepositoryRequest) (*Repository, error)
	Commit(context.Context, *CommitRequest) (*Commit, error)
	CommitStream(*CommitRequest, grpc.ServerStreamingServer[Progress]) error
	ListCommits(context.Context, *ListCommitsRequest) (*ListCommitsResponse, error)
	GetCommit(context.Context, *GetCommitRequest) (*Commit, error)
	Restore(context.Context, *RestoreRequest) (*RestoreResponse, error)
	RestoreStream(*RestoreRequest, grpc.ServerStreamingServer[Progress]) error
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	GetFile(*GetFileRequest, grpc.ServerStreamingServer[GetFileChunk]) error
	Diff(context.Context, *DiffRequest) (*DiffResponse, error)
	CreateMount(context.Context, *CreateMountRequest) (*Mount, error)
	GetMount(context.Context, *GetMountRequest) (*Mount, error)
	ListMounts(context.Context, *emptypb.Empty) (*ListMountsResponse, error)
	Unmount(context.Context, *UnmountRequest) (*emptypb.Empty, error)
	Shutdown(context.Context, *ShutdownRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedFvs2DServer()
}

// UnimplementedFvs2DServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFvs2DServer struct{}

func (UnimplementedFvs2DServer) Probe(context.Context, *emptypb.Empty) (*ProbeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Probe not implemented")
}
func (UnimplementedFvs2DServer) InitRepository(context.Context, *InitRepositoryRequest) (*Repository, error) {
	return nil, status.Error(codes.Unimplemented, "method InitRepository not implemented")
}
func (UnimplementedFvs2DServer) Commit(context.Context, *CommitRequest) (*Commit, error) {
	return nil, status.Error(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedFvs2DServer) CommitStream(*CommitRequest, grpc.ServerStreamingServer[Progress]) error {
	return status.Error(codes.Unimplemented, "method CommitStream not implemented")
}
func (UnimplementedFvs2DServer) ListCommits(context.Context, *ListCommitsRequest) (*ListCommitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCommits not implemented")
}
func (UnimplementedFvs2DServer) GetCommit(context.Context, *GetCommitRequest) (*Commit, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommit not implemented")
}
func (UnimplementedFvs2DServer) Restore(context.Context, *RestoreRequest) (*RestoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedFvs2DServer) RestoreStream(*RestoreRequest, grpc.ServerStreamingServer[Progress]) error {
	return status.Error(codes.Unimplemented, "method RestoreStream not implemented")
}
func (UnimplementedFvs2DServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedFvs2DServer) GetFile(*GetFileRequest, grpc.ServerStreamingServer[GetFileChunk]) error {
	return status.Error(codes.Unimplemented, "method GetFile not implemented")
}
func (UnimplementedFvs2DServer) Diff(context.Context, *DiffRequest) (*DiffResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Diff not implemented")
}
func (UnimplementedFvs2DServer) CreateMount(context.Context, *CreateMountRequest) (*Mount, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMount not implemented")
}
func (UnimplementedFvs2DServer) GetMount(context.Context, *GetMountRequest) (*Mount, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMount not implemented")
}
func (UnimplementedFvs2DServer) ListMounts(context.Context, *emptypb.Empty) (*ListMountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMounts not implemented")
}
func (UnimplementedFvs2DServer) Unmount(context.Context, *UnmountRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Unmount not implemented")
}
func (UnimplementedFvs2DServer) Shutdown(context.Context, *ShutdownRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedFvs2DServer) mustEmbedUnimplementedFvs2DServer() {}
func (UnimplementedFvs2DServer) testEmbeddedByValue()               {}

// UnsafeFvs2DServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Fvs2DServer will
// result in compilation errors.
type UnsafeFvs2DServer interface {
	mustEmbedUnimplementedFvs2DServer()
}

func RegisterFvs2DServer(s grpc.ServiceRegistrar, srv Fvs2DServer) {
	// If the following call panics, it indicates UnimplementedFvs2DServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Fvs2D_ServiceDesc, srv)
}

func _Fvs2D_Probe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Fvs2DServer).Probe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fvs2D_Probe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Fvs2DServer).Probe(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fvs2D_InitRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Fvs2DServer).InitRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fvs2D_InitRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Fvs2DServer).InitRepository(ctx, req.(*InitRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fvs2D_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Fvs2DServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fvs2D_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Fvs2DServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fvs2D_CommitStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CommitRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(Fvs2DServer).CommitStream(m, &grpc.GenericServerStream[CommitRequest, Progress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Fvs2D_CommitStreamServer = grpc.ServerStreamingServer[Progress]

func _Fvs2D_ListCommits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Fvs2DServer).ListCommits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fvs2D_ListCommits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Fvs2DServer).ListCommits(ctx, req.(*ListCommitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fvs2D_GetCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Fvs2DServer).GetCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fvs2D_GetCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Fvs2DServer).GetCommit(ctx, req.(*GetCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fvs2D_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Fvs2DServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fvs2D_Restore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Fvs2DServer).Restore(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fvs2D_RestoreStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RestoreRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(Fvs2DServer).RestoreStream(m, &grpc.GenericServerStream[RestoreRequest, Progress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Fvs2D_RestoreStreamServer = grpc.ServerStreamingServer[Progress]

func _Fvs2D_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Fvs2DServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fvs2D_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Fvs2DServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fvs2D_GetFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(Fvs2DServer).GetFile(m, &grpc.GenericServerStream[GetFileRequest, GetFileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Fvs2D_GetFileServer = grpc.ServerStreamingServer[GetFileChunk]

func _Fvs2D_Diff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Fvs2DServer).Diff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fvs2D_Diff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Fvs2DServer).Diff(ctx, req.(*DiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fvs2D_CreateMount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Fvs2DServer).CreateMount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fvs2D_CreateMount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Fvs2DServer).CreateMount(ctx, req.(*CreateMountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fvs2D_GetMount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Fvs2DServer).GetMount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fvs2D_GetMount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Fvs2DServer).GetMount(ctx, req.(*GetMountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fvs2D_ListMounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Fvs2DServer).ListMounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fvs2D_ListMounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Fvs2DServer).ListMounts(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fvs2D_Unmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Fvs2DServer).Unmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fvs2D_Unmount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Fvs2DServer).Unmount(ctx, req.(*UnmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fvs2D_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Fvs2DServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fvs2D_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Fvs2DServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Fvs2D_ServiceDesc is the grpc.ServiceDesc for Fvs2D service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Fvs2D_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fvs2d.v1.Fvs2d",
	HandlerType: (*Fvs2DServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Probe",
			Handler:    _Fvs2D_Probe_Handler,
		},
		{
			MethodName: "InitRepository",
			Handler:    _Fvs2D_InitRepository_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _Fvs2D_Commit_Handler,
		},
		{
			MethodName: "ListCommits",
			Handler:    _Fvs2D_ListCommits_Handler,
		},
		{
			MethodName: "GetCommit",
			Handler:    _Fvs2D_GetCommit_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _Fvs2D_Restore_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _Fvs2D_ListFiles_Handler,
		},
		{
			MethodName: "Diff",
			Handler:    _Fvs2D_Diff_Handler,
		},
		{
			MethodName: "CreateMount",
			Handler:    _Fvs2D_CreateMount_Handler,
		},
		{
			MethodName: "GetMount",
			Handler:    _Fvs2D_GetMount_Handler,
		},
		{
			MethodName: "ListMounts",
			Handler:    _Fvs2D_ListMounts_Handler,
		},
		{
			MethodName: "Unmount",
			Handler:    _Fvs2D_Unmount_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Fvs2D_Shutdown_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CommitStream",
			Handler:       _Fvs2D_CommitStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RestoreStream",
			Handler:       _Fvs2D_RestoreStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetFile",
			Handler:       _Fvs2D_GetFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "fvs2d.proto",
}
