// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: fvs2d.proto

package fvs2dpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnmountMode int32

const (
	UnmountMode_UNMOUNT_MODE_NORMAL UnmountMode = 0
	UnmountMode_UNMOUNT_MODE_LAZY   UnmountMode = 1
)

// Enum value maps for UnmountMode.
var (
	UnmountMode_name = map[int32]string{
		0: "UNMOUNT_MODE_NORMAL",
		1: "UNMOUNT_MODE_LAZY",
	}
	UnmountMode_value = map[string]int32{
		"UNMOUNT_MODE_NORMAL": 0,
		"UNMOUNT_MODE_LAZY":   1,
	}
)

func (x UnmountMode) Enum() *UnmountMode {
	p := new(UnmountMode)
	*p = x
	return p
}

func (x UnmountMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnmountMode) Descriptor() protoreflect.EnumDescriptor {
	return file_fvs2d_proto_enumTypes[0].Descriptor()
}

func (UnmountMode) Type() protoreflect.EnumType {
	return &file_fvs2d_proto_enumTypes[0]
}

func (x UnmountMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnmountMode.Descriptor instead.
func (UnmountMode) EnumDescriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{0}
}

type ListCommitsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepositoryPath string                 `protobuf:"bytes,1,opt,name=repository_path,json=repositoryPath,proto3" json:"repository_path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListCommitsRequest) Reset() {
	*x = ListCommitsRequest{}
	mi := &file_fvs2d_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommitsRequest) ProtoMessage() {}

func (x *ListCommitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommitsRequest.ProtoReflect.Descriptor instead.
func (*ListCommitsRequest) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{0}
}

func (x *ListCommitsRequest) GetRepositoryPath() string {
	if x != nil {
		return x.RepositoryPath
	}
	return ""
}

type ListCommitsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commits       []*Commit              `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommitsResponse) Reset() {
	*x = ListCommitsResponse{}
	mi := &file_fvs2d_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommitsResponse) ProtoMessage() {}

func (x *ListCommitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommitsResponse.ProtoReflect.Descriptor instead.
func (*ListCommitsResponse) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{1}
}

func (x *ListCommitsResponse) GetCommits() []*Commit {
	if x != nil {
		return x.Commits
	}
	return nil
}

type RestoreRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RepositoryPath  string                 `protobuf:"bytes,1,opt,name=repository_path,json=repositoryPath,proto3" json:"repository_path,omitempty"`
	StateIdOrPrefix string                 `protobuf:"bytes,2,opt,name=state_id_or_prefix,json=stateIdOrPrefix,proto3" json:"state_id_or_prefix,omitempty"`
	// destination_path overrides the restore destination (default: the repo root).
	DestinationPath *string `protobuf:"bytes,3,opt,name=destination_path,json=destinationPath,proto3,oneof" json:"destination_path,omitempty"`
	// clean removes files in the destination that are not part of the state.
	Clean bool `protobuf:"varint,4,opt,name=clean,proto3" json:"clean,omitempty"`
	// reset moves HEAD to the restored state.
	Reset_        bool `protobuf:"varint,5,opt,name=reset,proto3" json:"reset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_fvs2d_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{2}
}

func (x *RestoreRequest) GetRepositoryPath() string {
	if x != nil {
		return x.RepositoryPath
	}
	return ""
}

func (x *RestoreRequest) GetStateIdOrPrefix() string {
	if x != nil {
		return x.StateIdOrPrefix
	}
	return ""
}

func (x *RestoreRequest) GetDestinationPath() string {
	if x != nil && x.DestinationPath != nil {
		return *x.DestinationPath
	}
	return ""
}

func (x *RestoreRequest) GetClean() bool {
	if x != nil {
		return x.Clean
	}
	return false
}

func (x *RestoreRequest) GetReset_() bool {
	if x != nil {
		return x.Reset_
	}
	return false
}

type RestoreResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StateId         string                 `protobuf:"bytes,1,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	DestinationPath string                 `protobuf:"bytes,2,opt,name=destination_path,json=destinationPath,proto3" json:"destination_path,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_fvs2d_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{3}
}

func (x *RestoreResponse) GetStateId() string {
	if x != nil {
		return x.StateId
	}
	return ""
}

func (x *RestoreResponse) GetDestinationPath() string {
	if x != nil {
		return x.DestinationPath
	}
	return ""
}

type InitRepositoryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepositoryPath string                 `protobuf:"bytes,1,opt,name=repository_path,json=repositoryPath,proto3" json:"repository_path,omitempty"`
	BlockSize      uint32                 `protobuf:"varint,2,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InitRepositoryRequest) Reset() {
	*x = InitRepositoryRequest{}
	mi := &file_fvs2d_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRepositoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRepositoryRequest) ProtoMessage() {}

func (x *InitRepositoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRepositoryRequest.ProtoReflect.Descriptor instead.
func (*InitRepositoryRequest) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{4}
}

func (x *InitRepositoryRequest) GetRepositoryPath() string {
	if x != nil {
		return x.RepositoryPath
	}
	return ""
}

func (x *InitRepositoryRequest) GetBlockSize() uint32 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

type Repository struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepositoryPath string                 `protobuf:"bytes,1,opt,name=repository_path,json=repositoryPath,proto3" json:"repository_path,omitempty"`
	BlockSize      uint32                 `protobuf:"varint,2,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Repository) Reset() {
	*x = Repository{}
	mi := &file_fvs2d_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{5}
}

func (x *Repository) GetRepositoryPath() string {
	if x != nil {
		return x.RepositoryPath
	}
	return ""
}

func (x *Repository) GetBlockSize() uint32 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

type CommitRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepositoryPath string                 `protobuf:"bytes,1,opt,name=repository_path,json=repositoryPath,proto3" json:"repository_path,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AllowEmpty     bool                   `protobuf:"varint,3,opt,name=allow_empty,json=allowEmpty,proto3" json:"allow_empty,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_fvs2d_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{6}
}

func (x *CommitRequest) GetRepositoryPath() string {
	if x != nil {
		return x.RepositoryPath
	}
	return ""
}

func (x *CommitRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommitRequest) GetAllowEmpty() bool {
	if x != nil {
		return x.AllowEmpty
	}
	return false
}

type Commit struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepositoryPath string                 `protobuf:"bytes,1,opt,name=repository_path,json=repositoryPath,proto3" json:"repository_path,omitempty"`
	StateId        string                 `protobuf:"bytes,2,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FileCount      uint64                 `protobuf:"varint,4,opt,name=file_count,json=fileCount,proto3" json:"file_count,omitempty"`
	Message        string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Commit) Reset() {
	*x = Commit{}
	mi := &file_fvs2d_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit) ProtoMessage() {}

func (x *Commit) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit.ProtoReflect.Descriptor instead.
func (*Commit) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{7}
}

func (x *Commit) GetRepositoryPath() string {
	if x != nil {
		return x.RepositoryPath
	}
	return ""
}

func (x *Commit) GetStateId() string {
	if x != nil {
		return x.StateId
	}
	return ""
}

func (x *Commit) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Commit) GetFileCount() uint64 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

func (x *Commit) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProbeResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	DaemonVersion        string                 `protobuf:"bytes,1,opt,name=daemon_version,json=daemonVersion,proto3" json:"daemon_version,omitempty"`
	Pid                  uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	StartedAt            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FuseBackendAvailable bool                   `protobuf:"varint,4,opt,name=fuse_backend_available,json=fuseBackendAvailable,proto3" json:"fuse_backend_available,omitempty"`
	DevFuseAccessible    bool                   `protobuf:"varint,5,opt,name=dev_fuse_accessible,json=devFuseAccessible,proto3" json:"dev_fuse_accessible,omitempty"`
	FusermountAvailable  bool                   `protobuf:"varint,6,opt,name=fusermount_available,json=fusermountAvailable,proto3" json:"fusermount_available,omitempty"`
	RunningInFlatpak     bool                   `protobuf:"varint,7,opt,name=running_in_flatpak,json=runningInFlatpak,proto3" json:"running_in_flatpak,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ProbeResponse) Reset() {
	*x = ProbeResponse{}
	mi := &file_fvs2d_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResponse) ProtoMessage() {}

func (x *ProbeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResponse.ProtoReflect.Descriptor instead.
func (*ProbeResponse) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{8}
}

func (x *ProbeResponse) GetDaemonVersion() string {
	if x != nil {
		return x.DaemonVersion
	}
	return ""
}

func (x *ProbeResponse) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProbeResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ProbeResponse) GetFuseBackendAvailable() bool {
	if x != nil {
		return x.FuseBackendAvailable
	}
	return false
}

func (x *ProbeResponse) GetDevFuseAccessible() bool {
	if x != nil {
		return x.DevFuseAccessible
	}
	return false
}

func (x *ProbeResponse) GetFusermountAvailable() bool {
	if x != nil {
		return x.FusermountAvailable
	}
	return false
}

func (x *ProbeResponse) GetRunningInFlatpak() bool {
	if x != nil {
		return x.RunningInFlatpak
	}
	return false
}

type CommitSelector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Selector:
	//
	//	*CommitSelector_StateIdOrPrefix
	//	*CommitSelector_Branch
	Selector      isCommitSelector_Selector `protobuf_oneof:"selector"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitSelector) Reset() {
	*x = CommitSelector{}
	mi := &file_fvs2d_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitSelector) ProtoMessage() {}

func (x *CommitSelector) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitSelector.ProtoReflect.Descriptor instead.
func (*CommitSelector) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{9}
}

func (x *CommitSelector) GetSelector() isCommitSelector_Selector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *CommitSelector) GetStateIdOrPrefix() string {
	if x != nil {
		if x, ok := x.Selector.(*CommitSelector_StateIdOrPrefix); ok {
			return x.StateIdOrPrefix
		}
	}
	return ""
}

func (x *CommitSelector) GetBranch() string {
	if x != nil {
		if x, ok := x.Selector.(*CommitSelector_Branch); ok {
			return x.Branch
		}
	}
	return ""
}

type isCommitSelector_Selector interface {
	isCommitSelector_Selector()
}

type CommitSelector_StateIdOrPrefix struct {
	StateIdOrPrefix string `protobuf:"bytes,1,opt,name=state_id_or_prefix,json=stateIdOrPrefix,proto3,oneof"`
}

type CommitSelector_Branch struct {
	Branch string `protobuf:"bytes,2,opt,name=branch,proto3,oneof"`
}

func (*CommitSelector_StateIdOrPrefix) isCommitSelector_Selector() {}

func (*CommitSelector_Branch) isCommitSelector_Selector() {}

type Layer struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepositoryPath string                 `protobuf:"bytes,1,opt,name=repository_path,json=repositoryPath,proto3" json:"repository_path,omitempty"`
	Revision       *CommitSelector        `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Layer) Reset() {
	*x = Layer{}
	mi := &file_fvs2d_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Layer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layer) ProtoMessage() {}

func (x *Layer) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layer.ProtoReflect.Descriptor instead.
func (*Layer) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{10}
}

func (x *Layer) GetRepositoryPath() string {
	if x != nil {
		return x.RepositoryPath
	}
	return ""
}

func (x *Layer) GetRevision() *CommitSelector {
	if x != nil {
		return x.Revision
	}
	return nil
}

type MountSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountPoint    string                 `protobuf:"bytes,1,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	Layers        []*Layer               `protobuf:"bytes,2,rep,name=layers,proto3" json:"layers,omitempty"`
	UpperPath     *string                `protobuf:"bytes,3,opt,name=upper_path,json=upperPath,proto3,oneof" json:"upper_path,omitempty"`
	Debug         bool                   `protobuf:"varint,4,opt,name=debug,proto3" json:"debug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountSpec) Reset() {
	*x = MountSpec{}
	mi := &file_fvs2d_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountSpec) ProtoMessage() {}

func (x *MountSpec) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountSpec.ProtoReflect.Descriptor instead.
func (*MountSpec) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{11}
}

func (x *MountSpec) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *MountSpec) GetLayers() []*Layer {
	if x != nil {
		return x.Layers
	}
	return nil
}

func (x *MountSpec) GetUpperPath() string {
	if x != nil && x.UpperPath != nil {
		return *x.UpperPath
	}
	return ""
}

func (x *MountSpec) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

type CreateMountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *MountSpec             `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMountRequest) Reset() {
	*x = CreateMountRequest{}
	mi := &file_fvs2d_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMountRequest) ProtoMessage() {}

func (x *CreateMountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMountRequest.ProtoReflect.Descriptor instead.
func (*CreateMountRequest) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{12}
}

func (x *CreateMountRequest) GetSpec() *MountSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type ResolvedLayer struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepositoryPath string                 `protobuf:"bytes,1,opt,name=repository_path,json=repositoryPath,proto3" json:"repository_path,omitempty"`
	StateId        string                 `protobuf:"bytes,2,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	BlocksPath     string                 `protobuf:"bytes,3,opt,name=blocks_path,json=blocksPath,proto3" json:"blocks_path,omitempty"`
	BlockSize      uint32                 `protobuf:"varint,4,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolvedLayer) Reset() {
	*x = ResolvedLayer{}
	mi := &file_fvs2d_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedLayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedLayer) ProtoMessage() {}

func (x *ResolvedLayer) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedLayer.ProtoReflect.Descriptor instead.
func (*ResolvedLayer) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{13}
}

func (x *ResolvedLayer) GetRepositoryPath() string {
	if x != nil {
		return x.RepositoryPath
	}
	return ""
}

func (x *ResolvedLayer) GetStateId() string {
	if x != nil {
		return x.StateId
	}
	return ""
}

func (x *ResolvedLayer) GetBlocksPath() string {
	if x != nil {
		return x.BlocksPath
	}
	return ""
}

func (x *ResolvedLayer) GetBlockSize() uint32 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

type Mount struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Spec           *MountSpec             `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	ResolvedLayers []*ResolvedLayer       `protobuf:"bytes,3,rep,name=resolved_layers,json=resolvedLayers,proto3" json:"resolved_layers,omitempty"`
	NodeCount      uint64                 `protobuf:"varint,4,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	MountedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=mounted_at,json=mountedAt,proto3" json:"mounted_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Mount) Reset() {
	*x = Mount{}
	mi := &file_fvs2d_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mount) ProtoMessage() {}

func (x *Mount) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mount.ProtoReflect.Descriptor instead.
func (*Mount) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{14}
}

func (x *Mount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Mount) GetSpec() *MountSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Mount) GetResolvedLayers() []*ResolvedLayer {
	if x != nil {
		return x.ResolvedLayers
	}
	return nil
}

func (x *Mount) GetNodeCount() uint64 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *Mount) GetMountedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MountedAt
	}
	return nil
}

type GetMountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountId       string                 `protobuf:"bytes,1,opt,name=mount_id,json=mountId,proto3" json:"mount_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMountRequest) Reset() {
	*x = GetMountRequest{}
	mi := &file_fvs2d_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMountRequest) ProtoMessage() {}

func (x *GetMountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMountRequest.ProtoReflect.Descriptor instead.
func (*GetMountRequest) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{15}
}

func (x *GetMountRequest) GetMountId() string {
	if x != nil {
		return x.MountId
	}
	return ""
}

type ListMountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mounts        []*Mount               `protobuf:"bytes,1,rep,name=mounts,proto3" json:"mounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMountsResponse) Reset() {
	*x = ListMountsResponse{}
	mi := &file_fvs2d_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMountsResponse) ProtoMessage() {}

func (x *ListMountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMountsResponse.ProtoReflect.Descriptor instead.
func (*ListMountsResponse) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{16}
}

func (x *ListMountsResponse) GetMounts() []*Mount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

type UnmountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountId       string                 `protobuf:"bytes,1,opt,name=mount_id,json=mountId,proto3" json:"mount_id,omitempty"`
	Mode          UnmountMode            `protobuf:"varint,2,opt,name=mode,proto3,enum=fvs2d.v1.UnmountMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmountRequest) Reset() {
	*x = UnmountRequest{}
	mi := &file_fvs2d_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountRequest) ProtoMessage() {}

func (x *UnmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountRequest.ProtoReflect.Descriptor instead.
func (*UnmountRequest) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{17}
}

func (x *UnmountRequest) GetMountId() string {
	if x != nil {
		return x.MountId
	}
	return ""
}

func (x *UnmountRequest) GetMode() UnmountMode {
	if x != nil {
		return x.Mode
	}
	return UnmountMode_UNMOUNT_MODE_NORMAL
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          UnmountMode            `protobuf:"varint,1,opt,name=mode,proto3,enum=fvs2d.v1.UnmountMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_fvs2d_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{18}
}

func (x *ShutdownRequest) GetMode() UnmountMode {
	if x != nil {
		return x.Mode
	}
	return UnmountMode_UNMOUNT_MODE_NORMAL
}

var File_fvs2d_proto protoreflect.FileDescriptor

const file_fvs2d_proto_rawDesc = "" +
	"\n" +
	"\vfvs2d.proto\x12\bfvs2d.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"=\n" +
	"\x12ListCommitsRequest\x12'\n" +
	"\x0frepository_path\x18\x01 \x01(\tR\x0erepositoryPath\"A\n" +
	"\x13ListCommitsResponse\x12*\n" +
	"\acommits\x18\x01 \x03(\v2\x10.fvs2d.v1.CommitR\acommits\"\xd7\x01\n" +
	"\x0eRestoreRequest\x12'\n" +
	"\x0frepository_path\x18\x01 \x01(\tR\x0erepositoryPath\x12+\n" +
	"\x12state_id_or_prefix\x18\x02 \x01(\tR\x0fstateIdOrPrefix\x12.\n" +
	"\x10destination_path\x18\x03 \x01(\tH\x00R\x0fdestinationPath\x88\x01\x01\x12\x14\n" +
	"\x05clean\x18\x04 \x01(\bR\x05clean\x12\x14\n" +
	"\x05reset\x18\x05 \x01(\bR\x05resetB\x13\n" +
	"\x11_destination_path\"W\n" +
	"\x0fRestoreResponse\x12\x19\n" +
	"\bstate_id\x18\x01 \x01(\tR\astateId\x12)\n" +
	"\x10destination_path\x18\x02 \x01(\tR\x0fdestinationPath\"_\n" +
	"\x15InitRepositoryRequest\x12'\n" +
	"\x0frepository_path\x18\x01 \x01(\tR\x0erepositoryPath\x12\x1d\n" +
	"\n" +
	"block_size\x18\x02 \x01(\rR\tblockSize\"T\n" +
	"\n" +
	"Repository\x12'\n" +
	"\x0frepository_path\x18\x01 \x01(\tR\x0erepositoryPath\x12\x1d\n" +
	"\n" +
	"block_size\x18\x02 \x01(\rR\tblockSize\"s\n" +
	"\rCommitRequest\x12'\n" +
	"\x0frepository_path\x18\x01 \x01(\tR\x0erepositoryPath\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vallow_empty\x18\x03 \x01(\bR\n" +
	"allowEmpty\"\xc0\x01\n" +
	"\x06Commit\x12'\n" +
	"\x0frepository_path\x18\x01 \x01(\tR\x0erepositoryPath\x12\x19\n" +
	"\bstate_id\x18\x02 \x01(\tR\astateId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"file_count\x18\x04 \x01(\x04R\tfileCount\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\xca\x02\n" +
	"\rProbeResponse\x12%\n" +
	"\x0edaemon_version\x18\x01 \x01(\tR\rdaemonVersion\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x124\n" +
	"\x16fuse_backend_available\x18\x04 \x01(\bR\x14fuseBackendAvailable\x12.\n" +
	"\x13dev_fuse_accessible\x18\x05 \x01(\bR\x11devFuseAccessible\x121\n" +
	"\x14fusermount_available\x18\x06 \x01(\bR\x13fusermountAvailable\x12,\n" +
	"\x12running_in_flatpak\x18\a \x01(\bR\x10runningInFlatpak\"e\n" +
	"\x0eCommitSelector\x12-\n" +
	"\x12state_id_or_prefix\x18\x01 \x01(\tH\x00R\x0fstateIdOrPrefix\x12\x18\n" +
	"\x06branch\x18\x02 \x01(\tH\x00R\x06branchB\n" +
	"\n" +
	"\bselector\"f\n" +
	"\x05Layer\x12'\n" +
	"\x0frepository_path\x18\x01 \x01(\tR\x0erepositoryPath\x124\n" +
	"\brevision\x18\x02 \x01(\v2\x18.fvs2d.v1.CommitSelectorR\brevision\"\x9e\x01\n" +
	"\tMountSpec\x12\x1f\n" +
	"\vmount_point\x18\x01 \x01(\tR\n" +
	"mountPoint\x12'\n" +
	"\x06layers\x18\x02 \x03(\v2\x0f.fvs2d.v1.LayerR\x06layers\x12\"\n" +
	"\n" +
	"upper_path\x18\x03 \x01(\tH\x00R\tupperPath\x88\x01\x01\x12\x14\n" +
	"\x05debug\x18\x04 \x01(\bR\x05debugB\r\n" +
	"\v_upper_path\"=\n" +
	"\x12CreateMountRequest\x12'\n" +
	"\x04spec\x18\x01 \x01(\v2\x13.fvs2d.v1.MountSpecR\x04spec\"\x93\x01\n" +
	"\rResolvedLayer\x12'\n" +
	"\x0frepository_path\x18\x01 \x01(\tR\x0erepositoryPath\x12\x19\n" +
	"\bstate_id\x18\x02 \x01(\tR\astateId\x12\x1f\n" +
	"\vblocks_path\x18\x03 \x01(\tR\n" +
	"blocksPath\x12\x1d\n" +
	"\n" +
	"block_size\x18\x04 \x01(\rR\tblockSize\"\xdc\x01\n" +
	"\x05Mount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x04spec\x18\x02 \x01(\v2\x13.fvs2d.v1.MountSpecR\x04spec\x12@\n" +
	"\x0fresolved_layers\x18\x03 \x03(\v2\x17.fvs2d.v1.ResolvedLayerR\x0eresolvedLayers\x12\x1d\n" +
	"\n" +
	"node_count\x18\x04 \x01(\x04R\tnodeCount\x129\n" +
	"\n" +
	"mounted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tmountedAt\",\n" +
	"\x0fGetMountRequest\x12\x19\n" +
	"\bmount_id\x18\x01 \x01(\tR\amountId\"=\n" +
	"\x12ListMountsResponse\x12'\n" +
	"\x06mounts\x18\x01 \x03(\v2\x0f.fvs2d.v1.MountR\x06mounts\"V\n" +
	"\x0eUnmountRequest\x12\x19\n" +
	"\bmount_id\x18\x01 \x01(\tR\amountId\x12)\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x15.fvs2d.v1.UnmountModeR\x04mode\"<\n" +
	"\x0fShutdownRequest\x12)\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x15.fvs2d.v1.UnmountModeR\x04mode*=\n" +
	"\vUnmountMode\x12\x17\n" +
	"\x13UNMOUNT_MODE_NORMAL\x10\x00\x12\x15\n" +
	"\x11UNMOUNT_MODE_LAZY\x10\x012\x81\x05\n" +
	"\x05Fvs2d\x128\n" +
	"\x05Probe\x12\x16.google.protobuf.Empty\x1a\x17.fvs2d.v1.ProbeResponse\x12G\n" +
	"\x0eInitRepository\x12\x1f.fvs2d.v1.InitRepositoryRequest\x1a\x14.fvs2d.v1.Repository\x123\n" +
	"\x06Commit\x12\x17.fvs2d.v1.CommitRequest\x1a\x10.fvs2d.v1.Commit\x12J\n" +
	"\vListCommits\x12\x1c.fvs2d.v1.ListCommitsRequest\x1a\x1d.fvs2d.v1.ListCommitsResponse\x12>\n" +
	"\aRestore\x12\x18.fvs2d.v1.RestoreRequest\x1a\x19.fvs2d.v1.RestoreResponse\x12<\n" +
	"\vCreateMount\x12\x1c.fvs2d.v1.CreateMountRequest\x1a\x0f.fvs2d.v1.Mount\x126\n" +
	"\bGetMount\x12\x19.fvs2d.v1.GetMountRequest\x1a\x0f.fvs2d.v1.Mount\x12B\n" +
	"\n" +
	"ListMounts\x12\x16.google.protobuf.Empty\x1a\x1c.fvs2d.v1.ListMountsResponse\x12;\n" +
	"\aUnmount\x12\x18.fvs2d.v1.UnmountRequest\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\bShutdown\x12\x19.fvs2d.v1.ShutdownRequest\x1a\x16.google.protobuf.EmptyB Z\x1efvs2d/internal/fvs2dpb;fvs2dpbb\x06proto3"

var (
	file_fvs2d_proto_rawDescOnce sync.Once
	file_fvs2d_proto_rawDescData []byte
)

func file_fvs2d_proto_rawDescGZIP() []byte {
	file_fvs2d_proto_rawDescOnce.Do(func() {
		file_fvs2d_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fvs2d_proto_rawDesc), len(file_fvs2d_proto_rawDesc)))
	})
	return file_fvs2d_proto_rawDescData
}

var file_fvs2d_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fvs2d_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_fvs2d_proto_goTypes = []any{
	(UnmountMode)(0),              // 0: fvs2d.v1.UnmountMode
	(*ListCommitsRequest)(nil),    // 1: fvs2d.v1.ListCommitsRequest
	(*ListCommitsResponse)(nil),   // 2: fvs2d.v1.ListCommitsResponse
	(*RestoreRequest)(nil),        // 3: fvs2d.v1.RestoreRequest
	(*RestoreResponse)(nil),       // 4: fvs2d.v1.RestoreResponse
	(*InitRepositoryRequest)(nil), // 5: fvs2d.v1.InitRepositoryRequest
	(*Repository)(nil),            // 6: fvs2d.v1.Repository
	(*CommitRequest)(nil),         // 7: fvs2d.v1.CommitRequest
	(*Commit)(nil),                // 8: fvs2d.v1.Commit
	(*ProbeResponse)(nil),         // 9: fvs2d.v1.ProbeResponse
	(*CommitSelector)(nil),        // 10: fvs2d.v1.CommitSelector
	(*Layer)(nil),                 // 11: fvs2d.v1.Layer
	(*MountSpec)(nil),             // 12: fvs2d.v1.MountSpec
	(*CreateMountRequest)(nil),    // 13: fvs2d.v1.CreateMountRequest
	(*ResolvedLayer)(nil),         // 14: fvs2d.v1.ResolvedLayer
	(*Mount)(nil),                 // 15: fvs2d.v1.Mount
	(*GetMountRequest)(nil),       // 16: fvs2d.v1.GetMountRequest
	(*ListMountsResponse)(nil),    // 17: fvs2d.v1.ListMountsResponse
	(*UnmountRequest)(nil),        // 18: fvs2d.v1.UnmountRequest
	(*ShutdownRequest)(nil),       // 19: fvs2d.v1.ShutdownRequest
	(*timestamppb.Timestamp)(nil), // 20: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 21: google.protobuf.Empty
}
var file_fvs2d_proto_depIdxs = []int32{
	8,  // 0: fvs2d.v1.ListCommitsResponse.commits:type_name -> fvs2d.v1.Commit
	20, // 1: fvs2d.v1.Commit.created_at:type_name -> google.protobuf.Timestamp
	20, // 2: fvs2d.v1.ProbeResponse.started_at:type_name -> google.protobuf.Timestamp
	10, // 3: fvs2d.v1.Layer.revision:type_name -> fvs2d.v1.CommitSelector
	11, // 4: fvs2d.v1.MountSpec.layers:type_name -> fvs2d.v1.Layer
	12, // 5: fvs2d.v1.CreateMountRequest.spec:type_name -> fvs2d.v1.MountSpec
	12, // 6: fvs2d.v1.Mount.spec:type_name -> fvs2d.v1.MountSpec
	14, // 7: fvs2d.v1.Mount.resolved_layers:type_name -> fvs2d.v1.ResolvedLayer
	20, // 8: fvs2d.v1.Mount.mounted_at:type_name -> google.protobuf.Timestamp
	15, // 9: fvs2d.v1.ListMountsResponse.mounts:type_name -> fvs2d.v1.Mount
	0,  // 10: fvs2d.v1.UnmountRequest.mode:type_name -> fvs2d.v1.UnmountMode
	0,  // 11: fvs2d.v1.ShutdownRequest.mode:type_name -> fvs2d.v1.UnmountMode
	21, // 12: fvs2d.v1.Fvs2d.Probe:input_type -> google.protobuf.Empty
	5,  // 13: fvs2d.v1.Fvs2d.InitRepository:input_type -> fvs2d.v1.InitRepositoryRequest
	7,  // 14: fvs2d.v1.Fvs2d.Commit:input_type -> fvs2d.v1.CommitRequest
	1,  // 15: fvs2d.v1.Fvs2d.ListCommits:input_type -> fvs2d.v1.ListCommitsRequest
	3,  // 16: fvs2d.v1.Fvs2d.Restore:input_type -> fvs2d.v1.RestoreRequest
	13, // 17: fvs2d.v1.Fvs2d.CreateMount:input_type -> fvs2d.v1.CreateMountRequest
	16, // 18: fvs2d.v1.Fvs2d.GetMount:input_type -> fvs2d.v1.GetMountRequest
	21, // 19: fvs2d.v1.Fvs2d.ListMounts:input_type -> google.protobuf.Empty
	18, // 20: fvs2d.v1.Fvs2d.Unmount:input_type -> fvs2d.v1.UnmountRequest
	19, // 21: fvs2d.v1.Fvs2d.Shutdown:input_type -> fvs2d.v1.ShutdownRequest
	9,  // 22: fvs2d.v1.Fvs2d.Probe:output_type -> fvs2d.v1.ProbeResponse
	6,  // 23: fvs2d.v1.Fvs2d.InitRepository:output_type -> fvs2d.v1.Repository
	8,  // 24: fvs2d.v1.Fvs2d.Commit:output_type -> fvs2d.v1.Commit
	2,  // 25: fvs2d.v1.Fvs2d.ListCommits:output_type -> fvs2d.v1.ListCommitsResponse
	4,  // 26: fvs2d.v1.Fvs2d.Restore:output_type -> fvs2d.v1.RestoreResponse
	15, // 27: fvs2d.v1.Fvs2d.CreateMount:output_type -> fvs2d.v1.Mount
	15, // 28: fvs2d.v1.Fvs2d.GetMount:output_type -> fvs2d.v1.Mount
	17, // 29: fvs2d.v1.Fvs2d.ListMounts:output_type -> fvs2d.v1.ListMountsResponse
	21, // 30: fvs2d.v1.Fvs2d.Unmount:output_type -> google.protobuf.Empty
	21, // 31: fvs2d.v1.Fvs2d.Shutdown:output_type -> google.protobuf.Empty
	22, // [22:32] is the sub-list for method output_type
	12, // [12:22] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_fvs2d_proto_init() }
func file_fvs2d_proto_init() {
	if File_fvs2d_proto != nil {
		return
	}
	file_fvs2d_proto_msgTypes[2].OneofWrappers = []any{}
	file_fvs2d_proto_msgTypes[9].OneofWrappers = []any{
		(*CommitSelector_StateIdOrPrefix)(nil),
		(*CommitSelector_Branch)(nil),
	}
	file_fvs2d_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fvs2d_proto_rawDesc), len(file_fvs2d_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fvs2d_proto_goTypes,
		DependencyIndexes: file_fvs2d_proto_depIdxs,
		EnumInfos:         file_fvs2d_proto_enumTypes,
		MessageInfos:      file_fvs2d_proto_msgTypes,
	}.Build()
	File_fvs2d_proto = out.File
	file_fvs2d_proto_goTypes = nil
	file_fvs2d_proto_depIdxs = nil
}
