// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.6
// source: fvs2d.proto

package fvs2dpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Fvs2D_Probe_FullMethodName          = "/fvs2d.v1.Fvs2d/Probe"
	Fvs2D_InitRepository_FullMethodName = "/fvs2d.v1.Fvs2d/InitRepository"
	Fvs2D_Commit_FullMethodName         = "/fvs2d.v1.Fvs2d/Commit"
	Fvs2D_CreateMount_FullMethodName    = "/fvs2d.v1.Fvs2d/CreateMount"
	Fvs2D_GetMount_FullMethodName       = "/fvs2d.v1.Fvs2d/GetMount"
	Fvs2D_ListMounts_FullMethodName     = "/fvs2d.v1.Fvs2d/ListMounts"
	Fvs2D_Unmount_FullMethodName        = "/fvs2d.v1.Fvs2d/Unmount"
	Fvs2D_Shutdown_FullMethodName       = "/fvs2d.v1.Fvs2d/Shutdown"
)

// Fvs2DClient is the client API for Fvs2D service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Fvs2DClient interface {
	Probe(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ProbeResponse, error)
	InitRepository(ctx context.Context, in *InitRepositoryRequest, opts ...grpc.CallOption) (*Repository, error)
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*Revision, error)
	CreateMount(ctx context.Context, in *CreateMountRequest, opts ...grpc.CallOption) (*Mount, error)
	GetMount(ctx context.Context, in *GetMountRequest, opts ...grpc.CallOption) (*Mount, error)
	ListMounts(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListMountsResponse, error)
	Unmount(ctx context.Context, in *UnmountRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type fvs2DClient struct {
	cc grpc.ClientConnInterface
}

func NewFvs2DClient(cc grpc.ClientConnInterface) Fvs2DClient {
	return &fvs2DClient{cc}
}

func (c *fvs2DClient) Probe(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ProbeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbeResponse)
	err := c.cc.Invoke(ctx, Fvs2D_Probe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvs2DClient) InitRepository(ctx context.Context, in *InitRepositoryRequest, opts ...grpc.CallOption) (*Repository, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Repository)
	err := c.cc.Invoke(ctx, Fvs2D_InitRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvs2DClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*Revision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Revision)
	err := c.cc.Invoke(ctx, Fvs2D_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvs2DClient) CreateMount(ctx context.Context, in *CreateMountRequest, opts ...grpc.CallOption) (*Mount, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Mount)
	err := c.cc.Invoke(ctx, Fvs2D_CreateMount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvs2DClient) GetMount(ctx context.Context, in *GetMountRequest, opts ...grpc.CallOption) (*Mount, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Mount)
	err := c.cc.Invoke(ctx, Fvs2D_GetMount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvs2DClient) ListMounts(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListMountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMountsResponse)
	err := c.cc.Invoke(ctx, Fvs2D_ListMounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvs2DClient) Unmount(ctx context.Context, in *UnmountRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Fvs2D_Unmount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fvs2DClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Fvs2D_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Fvs2DServer is the server API for Fvs2D service.
// All implementations must embed UnimplementedFvs2DServer
// for forward compatibility.
type Fvs2DServer interface {
	Probe(context.Context, *emptypb.Empty) (*ProbeResponse, error)
	InitRepository(context.Context, *InitRepositoryRequest) (*Repository, error)
	Commit(context.Context, *CommitRequest) (*Revision, error)
	CreateMount(context.Context, *CreateMountRequest) (*Mount, error)
	GetMount(context.Context, *GetMountRequest) (*Mount, error)
	ListMounts(context.Context, *emptypb.Empty) (*ListMountsResponse, error)
	Unmount(context.Context, *UnmountRequest) (*emptypb.Empty, error)
	Shutdown(context.Context, *ShutdownRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedFvs2DServer()
}

// UnimplementedFvs2DServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFvs2DServer struct{}

func (UnimplementedFvs2DServer) Probe(context.Context, *emptypb.Empty) (*ProbeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Probe not implemented")
}
func (UnimplementedFvs2DServer) InitRepository(context.Context, *InitRepositoryRequest) (*Repository, error) {
	return nil, status.Error(codes.Unimplemented, "method InitRepository not implemented")
}
func (UnimplementedFvs2DServer) Commit(context.Context, *CommitRequest) (*Revision, error) {
	return nil, status.Error(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedFvs2DServer) CreateMount(context.Context, *CreateMountRequest) (*Mount, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMount not implemented")
}
func (UnimplementedFvs2DServer) GetMount(context.Context, *GetMountRequest) (*Mount, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMount not implemented")
}
func (UnimplementedFvs2DServer) ListMounts(context.Context, *emptypb.Empty) (*ListMountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMounts not implemented")
}
func (UnimplementedFvs2DServer) Unmount(context.Context, *UnmountRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Unmount not implemented")
}
func (UnimplementedFvs2DServer) Shutdown(context.Context, *ShutdownRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedFvs2DServer) mustEmbedUnimplementedFvs2DServer() {}
func (UnimplementedFvs2DServer) testEmbeddedByValue()               {}

// UnsafeFvs2DServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Fvs2DServer will
// result in compilation errors.
type UnsafeFvs2DServer interface {
	mustEmbedUnimplementedFvs2DServer()
}

func RegisterFvs2DServer(s grpc.ServiceRegistrar, srv Fvs2DServer) {
	// If the following call panics, it indicates UnimplementedFvs2DServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Fvs2D_ServiceDesc, srv)
}

func _Fvs2D_Probe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Fvs2DServer).Probe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fvs2D_Probe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Fvs2DServer).Probe(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fvs2D_InitRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Fvs2DServer).InitRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fvs2D_InitRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Fvs2DServer).InitRepository(ctx, req.(*InitRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fvs2D_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Fvs2DServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fvs2D_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Fvs2DServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fvs2D_CreateMount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Fvs2DServer).CreateMount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fvs2D_CreateMount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Fvs2DServer).CreateMount(ctx, req.(*CreateMountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fvs2D_GetMount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Fvs2DServer).GetMount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fvs2D_GetMount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Fvs2DServer).GetMount(ctx, req.(*GetMountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fvs2D_ListMounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Fvs2DServer).ListMounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fvs2D_ListMounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Fvs2DServer).ListMounts(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fvs2D_Unmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Fvs2DServer).Unmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fvs2D_Unmount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Fvs2DServer).Unmount(ctx, req.(*UnmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fvs2D_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Fvs2DServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fvs2D_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Fvs2DServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Fvs2D_ServiceDesc is the grpc.ServiceDesc for Fvs2D service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Fvs2D_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fvs2d.v1.Fvs2d",
	HandlerType: (*Fvs2DServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Probe",
			Handler:    _Fvs2D_Probe_Handler,
		},
		{
			MethodName: "InitRepository",
			Handler:    _Fvs2D_InitRepository_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _Fvs2D_Commit_Handler,
		},
		{
			MethodName: "CreateMount",
			Handler:    _Fvs2D_CreateMount_Handler,
		},
		{
			MethodName: "GetMount",
			Handler:    _Fvs2D_GetMount_Handler,
		},
		{
			MethodName: "ListMounts",
			Handler:    _Fvs2D_ListMounts_Handler,
		},
		{
			MethodName: "Unmount",
			Handler:    _Fvs2D_Unmount_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Fvs2D_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fvs2d.proto",
}
