// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: fvs2d.proto

package fvs2dpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnmountMode int32

const (
	UnmountMode_UNMOUNT_MODE_NORMAL UnmountMode = 0
	UnmountMode_UNMOUNT_MODE_LAZY   UnmountMode = 1
)

// Enum value maps for UnmountMode.
var (
	UnmountMode_name = map[int32]string{
		0: "UNMOUNT_MODE_NORMAL",
		1: "UNMOUNT_MODE_LAZY",
	}
	UnmountMode_value = map[string]int32{
		"UNMOUNT_MODE_NORMAL": 0,
		"UNMOUNT_MODE_LAZY":   1,
	}
)

func (x UnmountMode) Enum() *UnmountMode {
	p := new(UnmountMode)
	*p = x
	return p
}

func (x UnmountMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnmountMode) Descriptor() protoreflect.EnumDescriptor {
	return file_fvs2d_proto_enumTypes[0].Descriptor()
}

func (UnmountMode) Type() protoreflect.EnumType {
	return &file_fvs2d_proto_enumTypes[0]
}

func (x UnmountMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnmountMode.Descriptor instead.
func (UnmountMode) EnumDescriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{0}
}

type ProbeResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	DaemonVersion        string                 `protobuf:"bytes,1,opt,name=daemon_version,json=daemonVersion,proto3" json:"daemon_version,omitempty"`
	Pid                  uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	StartedAt            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FuseBackendAvailable bool                   `protobuf:"varint,4,opt,name=fuse_backend_available,json=fuseBackendAvailable,proto3" json:"fuse_backend_available,omitempty"`
	DevFuseAccessible    bool                   `protobuf:"varint,5,opt,name=dev_fuse_accessible,json=devFuseAccessible,proto3" json:"dev_fuse_accessible,omitempty"`
	FusermountAvailable  bool                   `protobuf:"varint,6,opt,name=fusermount_available,json=fusermountAvailable,proto3" json:"fusermount_available,omitempty"`
	RunningInFlatpak     bool                   `protobuf:"varint,7,opt,name=running_in_flatpak,json=runningInFlatpak,proto3" json:"running_in_flatpak,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ProbeResponse) Reset() {
	*x = ProbeResponse{}
	mi := &file_fvs2d_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResponse) ProtoMessage() {}

func (x *ProbeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResponse.ProtoReflect.Descriptor instead.
func (*ProbeResponse) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{0}
}

func (x *ProbeResponse) GetDaemonVersion() string {
	if x != nil {
		return x.DaemonVersion
	}
	return ""
}

func (x *ProbeResponse) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProbeResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ProbeResponse) GetFuseBackendAvailable() bool {
	if x != nil {
		return x.FuseBackendAvailable
	}
	return false
}

func (x *ProbeResponse) GetDevFuseAccessible() bool {
	if x != nil {
		return x.DevFuseAccessible
	}
	return false
}

func (x *ProbeResponse) GetFusermountAvailable() bool {
	if x != nil {
		return x.FusermountAvailable
	}
	return false
}

func (x *ProbeResponse) GetRunningInFlatpak() bool {
	if x != nil {
		return x.RunningInFlatpak
	}
	return false
}

type RevisionSelector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Selector:
	//
	//	*RevisionSelector_StateIdOrPrefix
	//	*RevisionSelector_Branch
	Selector      isRevisionSelector_Selector `protobuf_oneof:"selector"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevisionSelector) Reset() {
	*x = RevisionSelector{}
	mi := &file_fvs2d_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevisionSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevisionSelector) ProtoMessage() {}

func (x *RevisionSelector) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevisionSelector.ProtoReflect.Descriptor instead.
func (*RevisionSelector) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{1}
}

func (x *RevisionSelector) GetSelector() isRevisionSelector_Selector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *RevisionSelector) GetStateIdOrPrefix() string {
	if x != nil {
		if x, ok := x.Selector.(*RevisionSelector_StateIdOrPrefix); ok {
			return x.StateIdOrPrefix
		}
	}
	return ""
}

func (x *RevisionSelector) GetBranch() string {
	if x != nil {
		if x, ok := x.Selector.(*RevisionSelector_Branch); ok {
			return x.Branch
		}
	}
	return ""
}

type isRevisionSelector_Selector interface {
	isRevisionSelector_Selector()
}

type RevisionSelector_StateIdOrPrefix struct {
	StateIdOrPrefix string `protobuf:"bytes,1,opt,name=state_id_or_prefix,json=stateIdOrPrefix,proto3,oneof"`
}

type RevisionSelector_Branch struct {
	Branch string `protobuf:"bytes,2,opt,name=branch,proto3,oneof"`
}

func (*RevisionSelector_StateIdOrPrefix) isRevisionSelector_Selector() {}

func (*RevisionSelector_Branch) isRevisionSelector_Selector() {}

type Layer struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepositoryPath string                 `protobuf:"bytes,1,opt,name=repository_path,json=repositoryPath,proto3" json:"repository_path,omitempty"`
	Revision       *RevisionSelector      `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	BlocksPath     *string                `protobuf:"bytes,3,opt,name=blocks_path,json=blocksPath,proto3,oneof" json:"blocks_path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Layer) Reset() {
	*x = Layer{}
	mi := &file_fvs2d_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Layer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layer) ProtoMessage() {}

func (x *Layer) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layer.ProtoReflect.Descriptor instead.
func (*Layer) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{2}
}

func (x *Layer) GetRepositoryPath() string {
	if x != nil {
		return x.RepositoryPath
	}
	return ""
}

func (x *Layer) GetRevision() *RevisionSelector {
	if x != nil {
		return x.Revision
	}
	return nil
}

func (x *Layer) GetBlocksPath() string {
	if x != nil && x.BlocksPath != nil {
		return *x.BlocksPath
	}
	return ""
}

type MountSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountPoint    string                 `protobuf:"bytes,1,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	Layers        []*Layer               `protobuf:"bytes,2,rep,name=layers,proto3" json:"layers,omitempty"`
	UpperPath     *string                `protobuf:"bytes,3,opt,name=upper_path,json=upperPath,proto3,oneof" json:"upper_path,omitempty"`
	Debug         bool                   `protobuf:"varint,4,opt,name=debug,proto3" json:"debug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountSpec) Reset() {
	*x = MountSpec{}
	mi := &file_fvs2d_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountSpec) ProtoMessage() {}

func (x *MountSpec) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountSpec.ProtoReflect.Descriptor instead.
func (*MountSpec) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{3}
}

func (x *MountSpec) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *MountSpec) GetLayers() []*Layer {
	if x != nil {
		return x.Layers
	}
	return nil
}

func (x *MountSpec) GetUpperPath() string {
	if x != nil && x.UpperPath != nil {
		return *x.UpperPath
	}
	return ""
}

func (x *MountSpec) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

type CreateMountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *MountSpec             `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMountRequest) Reset() {
	*x = CreateMountRequest{}
	mi := &file_fvs2d_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMountRequest) ProtoMessage() {}

func (x *CreateMountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMountRequest.ProtoReflect.Descriptor instead.
func (*CreateMountRequest) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMountRequest) GetSpec() *MountSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type ResolvedLayer struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepositoryPath string                 `protobuf:"bytes,1,opt,name=repository_path,json=repositoryPath,proto3" json:"repository_path,omitempty"`
	StateId        string                 `protobuf:"bytes,2,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	BlocksPath     string                 `protobuf:"bytes,3,opt,name=blocks_path,json=blocksPath,proto3" json:"blocks_path,omitempty"`
	BlockSize      uint32                 `protobuf:"varint,4,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolvedLayer) Reset() {
	*x = ResolvedLayer{}
	mi := &file_fvs2d_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedLayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedLayer) ProtoMessage() {}

func (x *ResolvedLayer) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedLayer.ProtoReflect.Descriptor instead.
func (*ResolvedLayer) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{5}
}

func (x *ResolvedLayer) GetRepositoryPath() string {
	if x != nil {
		return x.RepositoryPath
	}
	return ""
}

func (x *ResolvedLayer) GetStateId() string {
	if x != nil {
		return x.StateId
	}
	return ""
}

func (x *ResolvedLayer) GetBlocksPath() string {
	if x != nil {
		return x.BlocksPath
	}
	return ""
}

func (x *ResolvedLayer) GetBlockSize() uint32 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

type Mount struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Spec           *MountSpec             `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	ResolvedLayers []*ResolvedLayer       `protobuf:"bytes,3,rep,name=resolved_layers,json=resolvedLayers,proto3" json:"resolved_layers,omitempty"`
	NodeCount      uint64                 `protobuf:"varint,4,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	MountedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=mounted_at,json=mountedAt,proto3" json:"mounted_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Mount) Reset() {
	*x = Mount{}
	mi := &file_fvs2d_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mount) ProtoMessage() {}

func (x *Mount) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mount.ProtoReflect.Descriptor instead.
func (*Mount) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{6}
}

func (x *Mount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Mount) GetSpec() *MountSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Mount) GetResolvedLayers() []*ResolvedLayer {
	if x != nil {
		return x.ResolvedLayers
	}
	return nil
}

func (x *Mount) GetNodeCount() uint64 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *Mount) GetMountedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MountedAt
	}
	return nil
}

type GetMountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountId       string                 `protobuf:"bytes,1,opt,name=mount_id,json=mountId,proto3" json:"mount_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMountRequest) Reset() {
	*x = GetMountRequest{}
	mi := &file_fvs2d_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMountRequest) ProtoMessage() {}

func (x *GetMountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMountRequest.ProtoReflect.Descriptor instead.
func (*GetMountRequest) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{7}
}

func (x *GetMountRequest) GetMountId() string {
	if x != nil {
		return x.MountId
	}
	return ""
}

type ListMountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mounts        []*Mount               `protobuf:"bytes,1,rep,name=mounts,proto3" json:"mounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMountsResponse) Reset() {
	*x = ListMountsResponse{}
	mi := &file_fvs2d_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMountsResponse) ProtoMessage() {}

func (x *ListMountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMountsResponse.ProtoReflect.Descriptor instead.
func (*ListMountsResponse) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{8}
}

func (x *ListMountsResponse) GetMounts() []*Mount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

type UnmountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountId       string                 `protobuf:"bytes,1,opt,name=mount_id,json=mountId,proto3" json:"mount_id,omitempty"`
	Mode          UnmountMode            `protobuf:"varint,2,opt,name=mode,proto3,enum=fvs2d.v1.UnmountMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmountRequest) Reset() {
	*x = UnmountRequest{}
	mi := &file_fvs2d_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountRequest) ProtoMessage() {}

func (x *UnmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountRequest.ProtoReflect.Descriptor instead.
func (*UnmountRequest) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{9}
}

func (x *UnmountRequest) GetMountId() string {
	if x != nil {
		return x.MountId
	}
	return ""
}

func (x *UnmountRequest) GetMode() UnmountMode {
	if x != nil {
		return x.Mode
	}
	return UnmountMode_UNMOUNT_MODE_NORMAL
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          UnmountMode            `protobuf:"varint,1,opt,name=mode,proto3,enum=fvs2d.v1.UnmountMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_fvs2d_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fvs2d_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_fvs2d_proto_rawDescGZIP(), []int{10}
}

func (x *ShutdownRequest) GetMode() UnmountMode {
	if x != nil {
		return x.Mode
	}
	return UnmountMode_UNMOUNT_MODE_NORMAL
}

var File_fvs2d_proto protoreflect.FileDescriptor

const file_fvs2d_proto_rawDesc = "" +
	"\n" +
	"\vfvs2d.proto\x12\bfvs2d.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xca\x02\n" +
	"\rProbeResponse\x12%\n" +
	"\x0edaemon_version\x18\x01 \x01(\tR\rdaemonVersion\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x124\n" +
	"\x16fuse_backend_available\x18\x04 \x01(\bR\x14fuseBackendAvailable\x12.\n" +
	"\x13dev_fuse_accessible\x18\x05 \x01(\bR\x11devFuseAccessible\x121\n" +
	"\x14fusermount_available\x18\x06 \x01(\bR\x13fusermountAvailable\x12,\n" +
	"\x12running_in_flatpak\x18\a \x01(\bR\x10runningInFlatpak\"g\n" +
	"\x10RevisionSelector\x12-\n" +
	"\x12state_id_or_prefix\x18\x01 \x01(\tH\x00R\x0fstateIdOrPrefix\x12\x18\n" +
	"\x06branch\x18\x02 \x01(\tH\x00R\x06branchB\n" +
	"\n" +
	"\bselector\"\x9e\x01\n" +
	"\x05Layer\x12'\n" +
	"\x0frepository_path\x18\x01 \x01(\tR\x0erepositoryPath\x126\n" +
	"\brevision\x18\x02 \x01(\v2\x1a.fvs2d.v1.RevisionSelectorR\brevision\x12$\n" +
	"\vblocks_path\x18\x03 \x01(\tH\x00R\n" +
	"blocksPath\x88\x01\x01B\x0e\n" +
	"\f_blocks_path\"\x9e\x01\n" +
	"\tMountSpec\x12\x1f\n" +
	"\vmount_point\x18\x01 \x01(\tR\n" +
	"mountPoint\x12'\n" +
	"\x06layers\x18\x02 \x03(\v2\x0f.fvs2d.v1.LayerR\x06layers\x12\"\n" +
	"\n" +
	"upper_path\x18\x03 \x01(\tH\x00R\tupperPath\x88\x01\x01\x12\x14\n" +
	"\x05debug\x18\x04 \x01(\bR\x05debugB\r\n" +
	"\v_upper_path\"=\n" +
	"\x12CreateMountRequest\x12'\n" +
	"\x04spec\x18\x01 \x01(\v2\x13.fvs2d.v1.MountSpecR\x04spec\"\x93\x01\n" +
	"\rResolvedLayer\x12'\n" +
	"\x0frepository_path\x18\x01 \x01(\tR\x0erepositoryPath\x12\x19\n" +
	"\bstate_id\x18\x02 \x01(\tR\astateId\x12\x1f\n" +
	"\vblocks_path\x18\x03 \x01(\tR\n" +
	"blocksPath\x12\x1d\n" +
	"\n" +
	"block_size\x18\x04 \x01(\rR\tblockSize\"\xdc\x01\n" +
	"\x05Mount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x04spec\x18\x02 \x01(\v2\x13.fvs2d.v1.MountSpecR\x04spec\x12@\n" +
	"\x0fresolved_layers\x18\x03 \x03(\v2\x17.fvs2d.v1.ResolvedLayerR\x0eresolvedLayers\x12\x1d\n" +
	"\n" +
	"node_count\x18\x04 \x01(\x04R\tnodeCount\x129\n" +
	"\n" +
	"mounted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tmountedAt\",\n" +
	"\x0fGetMountRequest\x12\x19\n" +
	"\bmount_id\x18\x01 \x01(\tR\amountId\"=\n" +
	"\x12ListMountsResponse\x12'\n" +
	"\x06mounts\x18\x01 \x03(\v2\x0f.fvs2d.v1.MountR\x06mounts\"V\n" +
	"\x0eUnmountRequest\x12\x19\n" +
	"\bmount_id\x18\x01 \x01(\tR\amountId\x12)\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x15.fvs2d.v1.UnmountModeR\x04mode\"<\n" +
	"\x0fShutdownRequest\x12)\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x15.fvs2d.v1.UnmountModeR\x04mode*=\n" +
	"\vUnmountMode\x12\x17\n" +
	"\x13UNMOUNT_MODE_NORMAL\x10\x00\x12\x15\n" +
	"\x11UNMOUNT_MODE_LAZY\x10\x012\xf7\x02\n" +
	"\x05Fvs2d\x128\n" +
	"\x05Probe\x12\x16.google.protobuf.Empty\x1a\x17.fvs2d.v1.ProbeResponse\x12<\n" +
	"\vCreateMount\x12\x1c.fvs2d.v1.CreateMountRequest\x1a\x0f.fvs2d.v1.Mount\x126\n" +
	"\bGetMount\x12\x19.fvs2d.v1.GetMountRequest\x1a\x0f.fvs2d.v1.Mount\x12B\n" +
	"\n" +
	"ListMounts\x12\x16.google.protobuf.Empty\x1a\x1c.fvs2d.v1.ListMountsResponse\x12;\n" +
	"\aUnmount\x12\x18.fvs2d.v1.UnmountRequest\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\bShutdown\x12\x19.fvs2d.v1.ShutdownRequest\x1a\x16.google.protobuf.EmptyB Z\x1efvs2d/internal/fvs2dpb;fvs2dpbb\x06proto3"

var (
	file_fvs2d_proto_rawDescOnce sync.Once
	file_fvs2d_proto_rawDescData []byte
)

func file_fvs2d_proto_rawDescGZIP() []byte {
	file_fvs2d_proto_rawDescOnce.Do(func() {
		file_fvs2d_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fvs2d_proto_rawDesc), len(file_fvs2d_proto_rawDesc)))
	})
	return file_fvs2d_proto_rawDescData
}

var file_fvs2d_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fvs2d_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_fvs2d_proto_goTypes = []any{
	(UnmountMode)(0),              // 0: fvs2d.v1.UnmountMode
	(*ProbeResponse)(nil),         // 1: fvs2d.v1.ProbeResponse
	(*RevisionSelector)(nil),      // 2: fvs2d.v1.RevisionSelector
	(*Layer)(nil),                 // 3: fvs2d.v1.Layer
	(*MountSpec)(nil),             // 4: fvs2d.v1.MountSpec
	(*CreateMountRequest)(nil),    // 5: fvs2d.v1.CreateMountRequest
	(*ResolvedLayer)(nil),         // 6: fvs2d.v1.ResolvedLayer
	(*Mount)(nil),                 // 7: fvs2d.v1.Mount
	(*GetMountRequest)(nil),       // 8: fvs2d.v1.GetMountRequest
	(*ListMountsResponse)(nil),    // 9: fvs2d.v1.ListMountsResponse
	(*UnmountRequest)(nil),        // 10: fvs2d.v1.UnmountRequest
	(*ShutdownRequest)(nil),       // 11: fvs2d.v1.ShutdownRequest
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 13: google.protobuf.Empty
}
var file_fvs2d_proto_depIdxs = []int32{
	12, // 0: fvs2d.v1.ProbeResponse.started_at:type_name -> google.protobuf.Timestamp
	2,  // 1: fvs2d.v1.Layer.revision:type_name -> fvs2d.v1.RevisionSelector
	3,  // 2: fvs2d.v1.MountSpec.layers:type_name -> fvs2d.v1.Layer
	4,  // 3: fvs2d.v1.CreateMountRequest.spec:type_name -> fvs2d.v1.MountSpec
	4,  // 4: fvs2d.v1.Mount.spec:type_name -> fvs2d.v1.MountSpec
	6,  // 5: fvs2d.v1.Mount.resolved_layers:type_name -> fvs2d.v1.ResolvedLayer
	12, // 6: fvs2d.v1.Mount.mounted_at:type_name -> google.protobuf.Timestamp
	7,  // 7: fvs2d.v1.ListMountsResponse.mounts:type_name -> fvs2d.v1.Mount
	0,  // 8: fvs2d.v1.UnmountRequest.mode:type_name -> fvs2d.v1.UnmountMode
	0,  // 9: fvs2d.v1.ShutdownRequest.mode:type_name -> fvs2d.v1.UnmountMode
	13, // 10: fvs2d.v1.Fvs2d.Probe:input_type -> google.protobuf.Empty
	5,  // 11: fvs2d.v1.Fvs2d.CreateMount:input_type -> fvs2d.v1.CreateMountRequest
	8,  // 12: fvs2d.v1.Fvs2d.GetMount:input_type -> fvs2d.v1.GetMountRequest
	13, // 13: fvs2d.v1.Fvs2d.ListMounts:input_type -> google.protobuf.Empty
	10, // 14: fvs2d.v1.Fvs2d.Unmount:input_type -> fvs2d.v1.UnmountRequest
	11, // 15: fvs2d.v1.Fvs2d.Shutdown:input_type -> fvs2d.v1.ShutdownRequest
	1,  // 16: fvs2d.v1.Fvs2d.Probe:output_type -> fvs2d.v1.ProbeResponse
	7,  // 17: fvs2d.v1.Fvs2d.CreateMount:output_type -> fvs2d.v1.Mount
	7,  // 18: fvs2d.v1.Fvs2d.GetMount:output_type -> fvs2d.v1.Mount
	9,  // 19: fvs2d.v1.Fvs2d.ListMounts:output_type -> fvs2d.v1.ListMountsResponse
	13, // 20: fvs2d.v1.Fvs2d.Unmount:output_type -> google.protobuf.Empty
	13, // 21: fvs2d.v1.Fvs2d.Shutdown:output_type -> google.protobuf.Empty
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_fvs2d_proto_init() }
func file_fvs2d_proto_init() {
	if File_fvs2d_proto != nil {
		return
	}
	file_fvs2d_proto_msgTypes[1].OneofWrappers = []any{
		(*RevisionSelector_StateIdOrPrefix)(nil),
		(*RevisionSelector_Branch)(nil),
	}
	file_fvs2d_proto_msgTypes[2].OneofWrappers = []any{}
	file_fvs2d_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fvs2d_proto_rawDesc), len(file_fvs2d_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fvs2d_proto_goTypes,
		DependencyIndexes: file_fvs2d_proto_depIdxs,
		EnumInfos:         file_fvs2d_proto_enumTypes,
		MessageInfos:      file_fvs2d_proto_msgTypes,
	}.Build()
	File_fvs2d_proto = out.File
	file_fvs2d_proto_goTypes = nil
	file_fvs2d_proto_depIdxs = nil
}
