// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: control.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

// Layer describes one lower layer selector of a stacked mount.
type Layer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`     // repo root containing .fvs2
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`   // explicit state id/prefix selector, if any
	Branch        string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"` // explicit branch selector, if any
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Layer) Reset() {
	*x = Layer{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Layer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layer) ProtoMessage() {}

func (x *Layer) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layer.ProtoReflect.Descriptor instead.
func (*Layer) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *Layer) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *Layer) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Layer) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mountpoint    string                 `protobuf:"bytes,1,opt,name=mountpoint,proto3" json:"mountpoint,omitempty"`                              // FUSE mountpoint
	Writable      bool                   `protobuf:"varint,2,opt,name=writable,proto3" json:"writable,omitempty"`                                 // true when a writable upper layer is present
	Upper         string                 `protobuf:"bytes,3,opt,name=upper,proto3" json:"upper,omitempty"`                                        // upper dir path (empty when read-only)
	Layers        []*Layer               `protobuf:"bytes,4,rep,name=layers,proto3" json:"layers,omitempty"`                                      // lower layers, low-to-high (stacked mount)
	Repo          string                 `protobuf:"bytes,5,opt,name=repo,proto3" json:"repo,omitempty"`                                          // single-repo mount: repo root
	State         string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`                                        // single-repo mount: selected state id/prefix
	Branch        string                 `protobuf:"bytes,7,opt,name=branch,proto3" json:"branch,omitempty"`                                      // single-repo mount: selected branch
	NodeCount     uint32                 `protobuf:"varint,8,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`              // number of nodes in the lower tree
	BlockSize     int32                  `protobuf:"varint,9,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`              // effective CoW block size
	Debug         bool                   `protobuf:"varint,10,opt,name=debug,proto3" json:"debug,omitempty"`                                      // daemon debug mode
	Pid           int32                  `protobuf:"varint,11,opt,name=pid,proto3" json:"pid,omitempty"`                                          // daemon process id
	UptimeSeconds int64                  `protobuf:"varint,12,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"` // seconds since the daemon started serving
	ApiVersion    string                 `protobuf:"bytes,13,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`           // control API version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *GetStatusResponse) GetMountpoint() string {
	if x != nil {
		return x.Mountpoint
	}
	return ""
}

func (x *GetStatusResponse) GetWritable() bool {
	if x != nil {
		return x.Writable
	}
	return false
}

func (x *GetStatusResponse) GetUpper() string {
	if x != nil {
		return x.Upper
	}
	return ""
}

func (x *GetStatusResponse) GetLayers() []*Layer {
	if x != nil {
		return x.Layers
	}
	return nil
}

func (x *GetStatusResponse) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *GetStatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetStatusResponse) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *GetStatusResponse) GetNodeCount() uint32 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *GetStatusResponse) GetBlockSize() int32 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

func (x *GetStatusResponse) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

func (x *GetStatusResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *GetStatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *GetStatusResponse) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

type ShutdownRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// lazy requests a lazy unmount (detach now, clean up when no longer busy).
	// Use it when the mountpoint may still be in use by another process.
	Lazy          bool `protobuf:"varint,1,opt,name=lazy,proto3" json:"lazy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *ShutdownRequest) GetLazy() bool {
	if x != nil {
		return x.Lazy
	}
	return false
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

func (x *ShutdownResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\x10fvs2d.control.v1\"\x0f\n" +
	"\rHealthRequest\" \n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x12\n" +
	"\x10GetStatusRequest\"I\n" +
	"\x05Layer\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\"\x86\x03\n" +
	"\x11GetStatusResponse\x12\x1e\n" +
	"\n" +
	"mountpoint\x18\x01 \x01(\tR\n" +
	"mountpoint\x12\x1a\n" +
	"\bwritable\x18\x02 \x01(\bR\bwritable\x12\x14\n" +
	"\x05upper\x18\x03 \x01(\tR\x05upper\x12/\n" +
	"\x06layers\x18\x04 \x03(\v2\x17.fvs2d.control.v1.LayerR\x06layers\x12\x12\n" +
	"\x04repo\x18\x05 \x01(\tR\x04repo\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x12\x16\n" +
	"\x06branch\x18\a \x01(\tR\x06branch\x12\x1d\n" +
	"\n" +
	"node_count\x18\b \x01(\rR\tnodeCount\x12\x1d\n" +
	"\n" +
	"block_size\x18\t \x01(\x05R\tblockSize\x12\x14\n" +
	"\x05debug\x18\n" +
	" \x01(\bR\x05debug\x12\x10\n" +
	"\x03pid\x18\v \x01(\x05R\x03pid\x12%\n" +
	"\x0euptime_seconds\x18\f \x01(\x03R\ruptimeSeconds\x12\x1f\n" +
	"\vapi_version\x18\r \x01(\tR\n" +
	"apiVersion\"%\n" +
	"\x0fShutdownRequest\x12\x12\n" +
	"\x04lazy\x18\x01 \x01(\bR\x04lazy\"\"\n" +
	"\x10ShutdownResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xff\x01\n" +
	"\aControl\x12K\n" +
	"\x06Health\x12\x1f.fvs2d.control.v1.HealthRequest\x1a .fvs2d.control.v1.HealthResponse\x12T\n" +
	"\tGetStatus\x12\".fvs2d.control.v1.GetStatusRequest\x1a#.fvs2d.control.v1.GetStatusResponse\x12Q\n" +
	"\bShutdown\x12!.fvs2d.control.v1.ShutdownRequest\x1a\".fvs2d.control.v1.ShutdownResponseB$Z\"fvs2d/internal/controlpb;controlpbb\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_control_proto_goTypes = []any{
	(*HealthRequest)(nil),     // 0: fvs2d.control.v1.HealthRequest
	(*HealthResponse)(nil),    // 1: fvs2d.control.v1.HealthResponse
	(*GetStatusRequest)(nil),  // 2: fvs2d.control.v1.GetStatusRequest
	(*Layer)(nil),             // 3: fvs2d.control.v1.Layer
	(*GetStatusResponse)(nil), // 4: fvs2d.control.v1.GetStatusResponse
	(*ShutdownRequest)(nil),   // 5: fvs2d.control.v1.ShutdownRequest
	(*ShutdownResponse)(nil),  // 6: fvs2d.control.v1.ShutdownResponse
}
var file_control_proto_depIdxs = []int32{
	3, // 0: fvs2d.control.v1.GetStatusResponse.layers:type_name -> fvs2d.control.v1.Layer
	0, // 1: fvs2d.control.v1.Control.Health:input_type -> fvs2d.control.v1.HealthRequest
	2, // 2: fvs2d.control.v1.Control.GetStatus:input_type -> fvs2d.control.v1.GetStatusRequest
	5, // 3: fvs2d.control.v1.Control.Shutdown:input_type -> fvs2d.control.v1.ShutdownRequest
	1, // 4: fvs2d.control.v1.Control.Health:output_type -> fvs2d.control.v1.HealthResponse
	4, // 5: fvs2d.control.v1.Control.GetStatus:output_type -> fvs2d.control.v1.GetStatusResponse
	6, // 6: fvs2d.control.v1.Control.Shutdown:output_type -> fvs2d.control.v1.ShutdownResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
